namespace SinaMN75U.InnerServices;

public interface ILocalizationService {
	string Get(string key, string? locale = null);
}

public class LocalizationService(IHttpContextAccessor httpContext) : ILocalizationService {
	private readonly Dictionary<string, string> _en = new() {
		// ===== Required =====
		{ "AddressRequired", "Address is Required." },
		{ "AmountRequired", "Amount Required." },
		{ "BankAccountRequired", "Bank Account is Required." },
		{ "BusinessTitleRequired", "Business Title is Required." },
		{ "CityCodeRequired", "City Code is Required." },
		{ "CommentRequired", "Comment is required." },
		{ "DailyPriceRequired", "Daily Price Required." },
		{ "DateRequired", "Date is Required" },
		{ "DescriptionRequired", "Description is Required" },
		{ "EmailRequired", "Email is required." },
		{ "EndDateRequired", "End Date is Required" },
		{ "EntrancePriceRequired", "Entrance Price Required." },
		{ "FirstNameRequired", "First Name is Required" },
		{ "HourlyPriceRequired", "Hourly Price Required." },
		{ "IBanRequired", "IBan Is Required." },
		{ "IdRequired", "Id is Required" },
		{ "LandlineRequired", "Landline is Required." },
		{ "LastNameRequired", "Last Name is Required" },
		{ "LicencePlateRequired", "LicencePlate Is Required." },
		{ "MerchantTitleRequired", "Merchant Name is Required." },
		{ "MccRequired", "Mcc is Required." },
		{ "NationalCodeRequired", "National Code is Required" },
		{ "NumberRequired", "Number Required." },
		{ "OtpRequired", "Otp is Required" },
		{ "OwnerNameRequired", "Owner Name is Required." },
		{ "PasswordRequired", "Please enter a password." },
		{ "PhoneNumberRequired", "Phone number is required." },
		{ "PriceRequired", "Price is Required" },
		{ "ProductRequired", "Product Is Required." },
		{ "Required", "Required" },
		{ "SerialRequired", "Serial Required." },
		{ "StartDateRequired", "Start Date is Required" },
		{ "SubTitleRequired", "Subtitle is Required" },
		{ "TagsRequired", "Tags is Required" },
		{ "TitleRequired", "Title is Required" },
		{ "TrackingNumberRequired", "Tracking Number Required." },
		{ "UserIdRequired", "User is Required" },
		{ "UserNameRequired", "UserName is required." },
		{ "ZipCodeRequired", "ZipCode Is Required." },

		// ===== Invalid =====
		{ "AddressNotValid", "Address is Not Valid." },
		{ "BankAccountNotValid", "Bank Account is Not Valid." },
		{ "BusinessTitleNotValid", "Business Title is Not Valid." },
		{ "CityCodeNotValid", "City Code is Not Valid." },
		{ "EmailInvalid", "Please enter a valid email." },
		{ "FirstNameInvalid", "First Name is Invalid" },
		{ "IBanInvalid", "IBan Is Invalid." },
		{ "LandlineNotValid", "Landline is Not Valid." },
		{ "LastNameInvalid", "Last Name is Invalid" },
		{ "LicencePlateInvalid", "LicencePlate Is Invalid." },
		{ "MerchantTitleNotValid", "Merchant Name is Not Valid." },
		{ "MccNotValid", "Mcc is Required." },
		{ "NationalCodeInvalid", "National Code is Invalid" },
		{ "OwnerNameNotValid", "Owner Name is Not Valid." },
		{ "PasswordInvalid", "Password must be 6-100 characters." },
		{ "PhoneNumberInvalid", "Please enter a valid phone number." },
		{ "PhoneNumberNotValid", "Phone number is not valid." },
		{ "UserNameInvalid", "Username is invalid. Please try another." },
		{ "UserNameMinLength", "UserName is not valid." },
		{ "ZipCodeInvalid", "ZipCode Is Invalid." },
		{ "ZipCodeNotValid", "ZipCode Is Not Valid." },

		// ===== Duplicate =====
		{ "CodeIsDuplicated", "This Code already exist." },
		{ "EmailIsDuplicated", "This Email is already exist." },
		{ "IdIsDuplicated", "This Id is already exist." },
		{ "ImeiIsDuplicated", "This Imei is already exist." },
		{ "NationalCodeIsDuplicated", "This National Code is already exist." },
		{ "PhoneNumberIsDuplicated", "This Phone Number is already exist." },
		{ "SimCardNumberIsDuplicated", "This Sim Card Number is already exist." },
		{ "SimCardSerialIsDuplicated", "This Sim Card Serial is already exist." },
		{ "SlugIsDuplicated", "This Slug is already exist." },
		{ "TrackingNumberIsDuplicated", "This Tracking Number is already exist." },
		{ "UserNameIsDuplicated", "This UserName is already exist." },

		// ===== Not Found =====
		{ "AddressNotFound", "Address Not Found" },
		{ "BankAccountNotFound", "Bank Account Not Found." },
		{ "CategoryNotFound", "Category not found. Please try another." },
		{ "CommentNotFound", "Comment Not Found." },
		{ "ContentNotFound", "Content Not Found." },
		{ "ExamNotFound", "Exam Not Found." },
		{ "FollowRelationshipNotFound", "Error Finding the relation" },
		{ "ProductNotFound", "Product not found. Please check details." },
		{ "SenderWalletNotFound", "Sender Wallet Not Found" },
		{ "MerchantNotFound", "Merchant Not Found." },
		{ "TerminalNotFound", "Terminal Not Found." },
		{ "TerminalNotFoundCheckDetails", "Terminal Not Found. Check Your Details" },
		{ "UserNotFound", "Account not found. Please check your details." },
		{ "WalletNotFound", "Wallet Not Found." },

		// ===== Authentication & Authorization =====
		{ "AuthorizationRequired", "Please sign in to continue." },
		{ "InvalidCredentials", "Login Information is Wrong" },
		{ "InvalidAPIKey", "Invalid API key" },
		{ "MaxOtpReached", "Too many OTP requests. Please wait and try again." },
		{ "OtpInvalid", "Entered Otp is not Valid or Expired, Please try again." },
		{ "RefreshTokenRequired", "Refresh Token Required." },
		{ "TokenExpired", "Auth Token is Expired." },

		// ===== Success =====
		{ "AddressDeletedSuccessfully", "Address Deleted Successfully" },
		{ "AddressUpdatedSuccessfully", "Address Updated Successfully" },
		{ "FollowSuccess", "Your now Following " },
		{ "ProductDeleted", "Product removed successfully." },
		{ "TransferMoneyDone", "Transfer Money Successful" },
		{ "UnfollowSuccess", "You are no longer following " },
		{ "UserDeleted", "Account deleted successfully." },
		{ "YourDetailSubmittedSuccessfully", "Your Detail Submitted Successfully." },

		// ===== Business Logic =====
		{ "AddressWithThisZipCodeAlreadyExists", "Address with this ZipCode already exists." },
		{ "AlreadyBookmarked", "Already Bookmarked" },
		{ "AlreadyFollowingUser", "Already Following User" },
		{ "AtLeastOneUserRequired", "At Least One User Required" },
		{ "BalanceIsLow", "Your Balance is Not Enough." },
		{ "BeforeDateSelected", "Wrong Date Selected" },
		{ "CannotFollowYourself", "Cannot Follow Yourself" },
		{ "FutureDateSelected", "Future Date Selected" },
		{ "LicencePlateMinMaxLength", "Licence Plate can't be more than 10 Characters." },
		{ "NationalCodeNotMatchWithPhoneNumberOwner", "National Code is not Match with Phone Number Owner." },
		{ "PasswordMinLength", "Password must be at least 6 characters." },
		{ "ProductDeleteFailed", "Could not delete product. Please try later." },
		{ "ShahkarIsNotAvailableAtThisTime", "Shahkar is not Available at this Time, Please try again Later." },
		{ "UserAlreadyExist", "Account already exists. Would you like to log in?" },
		{ "WalletForThisUserAlreadyExists", "User Already has Wallet." },
		{ "ZipCodeMustBe10CharactersLong", "Zip Code must be 10 Characters Long." },

		// ===== System / API =====
		{ "InternalServerError", "Internal server error" },
		{ "InvalidBase64RequestBody", "Invalid base64 request body" },
		{ "InvalidJsonBody", "Invalid JSON body" },
		{ "InvalidRequestFormat", "Invalid request format" },
		{ "RequestTooLarge", "Request too large" },
		{ "SecurityError", "Security Error." },
		{ "SystemError", "System Error" },
		{ "ThirdPartyError", "Third Party Service Error." },
		{ "YouDoNotHaveClearanceToDoThisAction", "You Do Not have Clearance to do this Action." }
	};

	private readonly Dictionary<string, string> _fa = new() {
		// ===== Required =====
		{ "AddressRequired", "آدرس الزامی است" },
		{ "AmountRequired", "مبلغ الزامی است" },
		{ "BankAccountRequired", "شماره حساب الزامی است" },
		{ "BusinessTitleRequired", "عنوان کسب و کار الزامی است." },
		{ "CityCodeRequired", "کد شهر الزامی است" },
		{ "CommentRequired", "نظر الزامی است." },
		{ "DailyPriceRequired", "مبلغ روزانه الزامی است" },
		{ "DateRequired", "تاریخ الزامی است" },
		{ "DescriptionRequired", "توضیحات الزامی است" },
		{ "EmailRequired", "ایمیل الزامی است." },
		{ "EndDateRequired", "تاریخ پایان الزامی است" },
		{ "EntrancePriceRequired", "مبلغ ورودی الزامی است" },
		{ "FirstNameRequired", "نام الزامی است" },
		{ "HourlyPriceRequired", "مبلغ ساعتی الزامی است" },
		{ "IBanRequired", "شماره شبا الزامی است." },
		{ "IdRequired", "شناسه الزامی است" },
		{ "LandlineRequired", "شماره تلفن ثابت الزامی است" },
		{ "LastNameRequired", "نام خانوادگی الزامی است" },
		{ "LicencePlateRequired", "شماره پلاک الزامی است." },
		{ "MerchantTitleRequired", "نام پذیرنده الزامیست." },
		{ "MccRequired", "کد صنف الزامی است" },
		{ "NationalCodeRequired", "کد ملی الزامی است" },
		{ "NumberRequired", "شماره الزامی است" },
		{ "OtpRequired", "کد تایید الزامی است" },
		{ "OwnerNameRequired", "نام مالک فروشگاه الزامی است" },
		{ "OwnerPhoneNumberRequired", "شماره تلفن مالک الزامی است." },
		{ "PasswordRequired", "لطفاً رمز عبور را وارد کنید." },
		{ "PhoneNumberRequired", "شماره تلفن الزامی است." },
		{ "PriceRequired", "قیمت الزامی است" },
		{ "ProductRequired", "محصول الزامی است." },
		{ "Required", "مورد نیاز" },
		{ "SerialRequired", "سریال الزامی است" },
		{ "StartDateRequired", "تاریخ شروع الزامی است" },
		{ "SubTitleRequired", "عنوان فرعی الزامی است" },
		{ "TagsRequired", "برچسب‌ها الزامی است" },
		{ "TitleRequired", "عنوان الزامی است" },
		{ "TrackingNumberRequired", "کد رهگیری الزامی است" },
		{ "UserIdRequired", "کاربر الزامی است" },
		{ "UserNameRequired", "نام کاربری الزامی است." },
		{ "ZipCodeRequired", "کد پستی الزامی است." },

		// ===== Invalid =====
		{ "AddressNotValid", "آدرس صحیح نیست." },
		{ "BankAccountNotValid", "شماره حساب صحیح نیست." },
		{ "BusinessTitleNotValid", "عنوان کسب و کار صحیح نیست." },
		{ "CityCodeNotValid", "کد شهر صحیح نیست." },
		{ "EmailInvalid", "لطفاً یک ایمیل معتبر وارد کنید." },
		{ "FirstNameInvalid", "نام نامعتبر است" },
		{ "IBanInvalid", "شماره شبا اشتباه است." },
		{ "LandlineNotValid", "شماره تلفن ثابت صحیح نیست." },
		{ "LastNameInvalid", "نام خانوادگی نامعتبر است" },
		{ "LicencePlateInvalid", "شماره پلاک اشتباه است." },
		{ "MerchantTitleNotValid", "نام پذیرنده صحیح نیست." },
		{ "MccNotValid", "کد صنف صحیح نیست." },
		{ "NationalCodeInvalid", "کد ملی نامعتبر است" },
		{ "OwnerNameNotValid", "نام مالک فروشگاه صحیح نیست" },
		{ "OwnerPhoneNumberNotValid", "شماره تلفن مالک صحیح نیست." },
		{ "PasswordInvalid", "رمز عبور باید بین 6 تا 100 کاراکتر باشد." },
		{ "PhoneNumberInvalid", "لطفاً یک شماره تلفن معتبر وارد کنید." },
		{ "PhoneNumberNotValid", "شماره تلفن معتبر نیست." },
		{ "UserNameInvalid", "نام کاربری نامعتبر است. لطفاً دیگری را امتحان کنید." },
		{ "UserNameMinLength", "نام کاربری معتبر نیست." },
		{ "ZipCodeInvalid", "کد پستی اشتباه است." },
		{ "ZipCodeNotValid", "کد پستی صحیح نیست." },

		// ===== Duplicate =====
		{ "CodeIsDuplicated", "کد تکراری است." },
		{ "EmailIsDuplicated", "ایمیل تکراری است." },
		{ "IdIsDuplicated", "آیدی تکراری است." },
		{ "ImeiIsDuplicated", "IMEI تکراری است." },
		{ "NationalCodeIsDuplicated", "کد ملی تکراری است." },
		{ "PhoneNumberIsDuplicated", "شماره موبایل تکراری است." },
		{ "SimCardNumberIsDuplicated", "شماره سیمکارت تکراری است." },
		{ "SimCardSerialIsDuplicated", "سریال سیمکارت تکراری است." },
		{ "SlugIsDuplicated", "اسلاگ تکراری است." },
		{ "TrackingNumberIsDuplicated", "کد رهگیری تکراری است." },
		{ "UserNameIsDuplicated", "نام کاربری تکراری است." },

		// ===== Not Found =====
		{ "AddressNotFound", "آدرس یافت نشد" },
		{ "BankAccountNotFound", "حساب بانکی یافت نشد." },
		{ "CategoryNotFound", "دسته بندی یافت نشد. لطفاً دیگری را امتحان کنید." },
		{ "CommentNotFound", "نظر یافت نشد." },
		{ "ContentNotFound", "محتوا یافت نشد." },
		{ "ExamNotFound", "آزمون یافت نشد." },
		{ "FollowRelationshipNotFound", "خطا در یافتن رابطه" },
		{ "ProductNotFound", "محصول یافت نشد. لطفاً جزئیات را بررسی کنید." },
		{ "SenderWalletNotFound", "کیف پول فرستنده یافت نشد" },
		{ "MerchantNotFound", "پذیرنده یافت نشد." },
		{ "TerminalNotFound", "ترمینال یافت نشد." },
		{ "TerminalNotFoundCheckDetails", "ترمینال یافت نشد. لطفا اطلاعات خود را بررسی کنید." },
		{ "UserNotFound", "حساب کاربری یافت نشد. لطفاً جزئیات خود را بررسی کنید." },
		{ "WalletNotFound", "کیف پول یافت نشد." },

		// ===== Authentication & Authorization =====
		{ "AuthorizationRequired", "لطفاً برای ادامه وارد شوید." },
		{ "InvalidCredentials", "اطلاعات ورود اشتباه است" },
		{ "InvalidAPIKey", "کلید API نامعتبر است" },
		{ "MaxOtpReached", "تعداد درخواست‌های کد تایید زیاد است. لطفاً صبر کرده و دوباره امتحان کنید." },
		{ "OtpInvalid", "کد تایید وارد شده صحیح نیست یا منقضی شده. لطفا دوباره امتحان کنید." },
		{ "RefreshTokenRequired", "توکن الزامیست" },
		{ "TokenExpired", "توکن احراز هویت منقضی شده است." },

		// ===== Success =====
		{ "AddressDeletedSuccessfully", "آدرس با موفقیت حذف شد" },
		{ "AddressUpdatedSuccessfully", "آدرس با موفقیت به روز شد" },
		{ "FollowSuccess", "شما اکنون در حال فالو کردن هستید، " },
		{ "ProductDeleted", "محصول با موفقیت حذف شد." },
		{ "TransferMoneyDone", "انتقال پول با موفقیت انجام شد" },
		{ "UnfollowSuccess", "شما دیگر فالو نمی‌کنید، " },
		{ "UserDeleted", "حساب کاربری با موفقیت حذف شد." },
		{ "YourDetailSubmittedSuccessfully", "جزئیات شما با موفقیت ارسال شد." },

		// ===== Business Logic =====
		{ "AddressWithThisZipCodeAlreadyExists", "آدرسی با این کد پستی از قبل وجود دارد." },
		{ "AlreadyBookmarked", "از قبل بوکمارک شده است" },
		{ "AlreadyFollowingUser", "از قبل این کاربر را فالو می‌کنید" },
		{ "AtLeastOneUserRequired", "حداقل یک کاربر مورد نیاز است" },
		{ "BalanceIsLow", "موجودی شما کافی نیست." },
		{ "BeforeDateSelected", "تاریخ اشتباه انتخاب شده است" },
		{ "CannotFollowYourself", "امکان فالو کردن خودتان وجود ندارد" },
		{ "FutureDateSelected", "تاریخ آینده انتخاب شده است" },
		{ "LicencePlateMinMaxLength", "طول پلاک خودرو نمیتواند بیشتر از ۱۰ کاراکتر باشد." },
		{ "NationalCodeNotMatchWithPhoneNumberOwner", "کد ملی با صاحب شماره تلفن مطابقت ندارد." },
		{ "PasswordMinLength", "رمز عبور باید حداقل 6 کاراکتر باشد." },
		{ "ProductDeleteFailed", "حذف محصول امکان پذیر نبود. لطفاً بعداً دوباره امتحان کنید." },
		{ "ShahkarIsNotAvailableAtThisTime", "شاهکار در این زمان در دسترس نیست، لطفاً بعداً دوباره امتحان کنید." },
		{ "UserAlreadyExist", "حساب کاربری از قبل وجود دارد. آیا مایل به ورود هستید؟" },
		{ "WalletForThisUserAlreadyExists", "کاربر از قبل کیف پول دارد." },
		{ "ZipCodeMustBe10CharactersLong", "کد پستی باید 10 کاراکتر باشد." },

		// ===== System / API =====
		{ "InternalServerError", "خطای داخلی سرور" },
		{ "InvalidBase64RequestBody", "بدنه درخواست base64 نامعتبر است" },
		{ "InvalidJsonBody", "بدنه JSON نامعتبر است" },
		{ "InvalidRequestFormat", "قالب درخواست نامعتبر است" },
		{ "RequestTooLarge", "درخواست بیش از حد بزرگ است" },
		{ "SecurityError", "خطای امنیتی" },
		{ "SystemError", "خطای سیستم" },
		{ "ThirdPartyError", "خطای سامانه مرجع" },
		{ "YouDoNotHaveClearanceToDoThisAction", "شما مجاز به انجام این عملیات نیستید." }
	};

	public string Get(string key, string? locale = null) {
		string l = locale ?? httpContext.HttpContext?.Request.Headers["Locale"].FirstOrDefault() ?? "en";
		try {
			if (l == "fa") return _fa[key];
			return _en[key];
		}
		catch (Exception) {
			return string.Empty;
		}
	}
}