namespace SinaMN75U.InnerServices;

public interface ILocalizationService {
	string Get(string key, string? locale = null);
}

public class LocalizationService(IHttpContextAccessor httpContext) : ILocalizationService {
	private static readonly Dictionary<string, string> En = new() {
		// ===== Required =====
		{ "addressIsRequired", "Address is Required." },
		{ "amountRequired", "Amount Required." },
		{ "bankAccountIsRequired", "Bank Account is Required." },
		{ "businessTitleIsRequired", "Business Title is Required." },
		{ "brandIsRequired", "Brand is Required." },
		{ "brokerIsRequired", "Broker is Required." },
		{ "cityCodeIsRequired", "City Code is Required." },
		{ "commentIsRequired", "Comment is required." },
		{ "dailyPriceRequired", "Daily Price Required." },
		{ "dateIsRequired", "Date is Required" },
		{ "descriptionIsRequired", "Description is Required" },
		{ "emailIsRequired", "Email is required." },
		{ "endDateIsRequired", "End Date is Required" },
		{ "entrancePriceRequired", "Entrance Price Required." },
		{ "firstNameIsRequired", "First Name is Required" },
		{ "hourlyPriceRequired", "Hourly Price Required." },
		{ "iBanIsRequired", "IBan Is Required." },
		{ "idIsRequired", "Id is Required" },
		{ "terminalIdIsRequired", "Terminal Id is Required." },
		{ "landlineIsRequired", "Landline is Required." },
		{ "lastNameIsRequired", "Last Name is Required" },
		{ "licencePlateIsRequired", "LicencePlate Is Required." },
		{ "merchantNameIsRequired", "Merchant Name is Required." },
		{ "mccIsRequired", "Mcc is Required." },
		{ "nationalCodeIsRequired", "National Code is Required" },
		{ "numberRequired", "Number Required." },
		{ "otpIsRequired", "Otp is Required" },
		{ "ownerNameIsRequired", "Owner Name is Required." },
		{ "ownerPhoneNumberIsRequired", "Owner Phone Number is Required." },
		{ "pleaseEnterAPassword", "Please enter a password." },
		{ "phoneNumberIsRequired", "Phone number is required." },
		{ "priceIsRequired", "Price is Required" },
		{ "productIsRequired", "Product Is Required." },
		{ "required", "Required" },
		{ "serialIsRequired", "Serial Required." },
		{ "startDateIsRequired", "Start Date is Required" },
		{ "subtitleIsRequired", "Subtitle is Required" },
		{ "tagsIsRequired", "Tags is Required" },
		{ "titleIsRequired", "Title is Required" },
		{ "trackingNumberRequired", "Tracking Number Required." },
		{ "userIsRequired", "User is Required" },
		{ "userNameIsRequired", "UserName is required." },
		{ "zipCodeIsRequired", "ZipCode Is Required." },
		{ "fatherNameRequired", "Father Name Required." },
		{ "birthDateRequired", "BirthDate Required." },
		{ "invalidDateFormat", "Invalid Date Format." },
		{ "nationalCardFrontRequired", "National Card Front Required." },
		{ "nationalCardBackRequired", "National Card Back Required." },
		{ "birthCertificateFirstRequired", "Birth Certificate First Required." },
		{ "visualAuthenticationRequired", "Visual Authentication Required." },
		{ "signatureRequired", "Signature Required." },
		{ "billIdRequired", "Bill Id Required." },
		{ "paymentIdRequired", "Payment Id Required." },
		{ "modelIsRequired", "Model is Required." },
		{ "merchantIsRequired", "Merchant is Required." },

		// ===== Invalid =====
		{ "addressIsNotValid", "Address is Not Valid." },
		{ "bankAccountIsNotValid", "Bank Account is Not Valid." },
		{ "businessTitleIsNotValid", "Business Title is Not Valid." },
		{ "cityCodeIsNotValid", "City Code is Not Valid." },
		{ "pleaseEnterAValidEmail", "Please enter a valid email." },
		{ "firstNameIsInvalid", "First Name is Invalid" },
		{ "iBanIsInvalid", "IBan Is Invalid." },
		{ "landlineIsNotValid", "Landline is Not Valid." },
		{ "lastNameIsInvalid", "Last Name is Invalid" },
		{ "licencePlateIsInvalid", "LicencePlate Is Invalid." },
		{ "merchantNameIsNotValid", "Merchant Name is Not Valid." },
		{ "mccIsNotValid", "Mcc is Not Valid." },
		{ "nationalCodeIsInvalid", "National Code is Invalid" },
		{ "ownerNameIsNotValid", "Owner Name is Not Valid." },
		{ "ownerPhoneNumberIsNotValid", "Owner Phone Number is Not Valid." },
		{ "passwordMustBe6100Characters", "Password must be 6-100 characters." },
		{ "pleaseEnterAValidPhoneNumber", "Please enter a valid phone number." },
		{ "phoneNumberIsNotValid", "Phone number is not valid." },
		{ "usernameIsInvalidPleaseTryAnother", "Username is invalid. Please try another." },
		{ "userNameIsNotValid", "UserName is not valid." },
		{ "zipCodeIsInvalid", "ZipCode Is Invalid." },
		{ "zipCodeIsNotValid", "ZipCode Is Not Valid." },

		// ===== Duplicate =====
		{ "thisCodeAlreadyExists", "This Code already exists." },
		{ "thisEmailAlreadyExists", "This Email already exists." },
		{ "thisIdAlreadyExists", "This Id already exists." },
		{ "thisIMEIAlreadyExists", "This IMEI already exists." },
		{ "thisNationalCodeAlreadyExists", "This National Code already exists." },
		{ "thisPhoneNumberAlreadyExists", "This Phone Number already exists." },
		{ "thisSimCardNumberAlreadyExists", "This Sim Card Number already exists." },
		{ "thisSimCardSerialAlreadyExists", "This Sim Card Serial already exists." },
		{ "thisSlugAlreadyExists", "This Slug already exists." },
		{ "thisTerminalIdAlreadyExists", "This Terminal Id already exists." },
		{ "thisTrackingNumberAlreadyExists", "This Tracking Number already exists." },
		{ "thisNumberPlateAlreadyExists", "This Number Plate already exists." },
		{ "thisUserNameAlreadyExists", "This UserName already exists." },
		{ "thisRecordAlreadyExists", "This record already exists." },

		// ===== Not Found =====
		{ "addressNotFound", "Address Not Found" },
		{ "bankAccountNotFound", "Bank Account Not Found." },
		{ "categoryNotFoundPleaseTryAnother", "Category not found. Please try another." },
		{ "commentNotFound", "Comment Not Found." },
		{ "contentNotFound", "Content Not Found." },
		{ "contentUpdatedSuccessfully", "Content updated successfully." },
		{ "contentRemovedSuccessfully", "Content removed successfully." },
		{ "examNotFound", "Exam Not Found." },
		{ "errorFindingTheRelation", "Error Finding the relation" },
		{ "productNotFoundPleaseCheckDetails", "Product not found. Please check details." },
		{ "senderWalletNotFound", "Sender Wallet Not Found" },
		{ "merchantNotFound", "Merchant Not Found." },
		{ "terminalNotFound", "Terminal Not Found." },
		{ "terminalNotFoundCheckYourDetails", "Terminal Not Found. Check Your Details" },
		{ "terminalBrandNotFound", "Terminal Brand Not Found." },
		{ "terminalBrokerNotFound", "Terminal Broker Not Found." },
		{ "terminalBrandIsRequired", "Terminal Brand is Required" },
		{ "terminalBrokerIsRequired", "Terminal Broker is Required" },
		{ "printTheAgreementSignItAndSendItByPost", "Print the agreement, have both parties sign it and send it by post." },
		{ "TitleRequired", "Title Required." },
		{ "postalCodeIsRequired", "Postal Code is Required." },
		{ "registrationNumberIsRequired", "Registration Number is Required." },
		{ "representativeIsRequired", "Representative is Required." },
		{ "signatureIsRequired", "Signature is Required." },
		{ "logoIsRequired", "Logo is Required." },
		{ "ModelIsRequired", "Model is Required." },
		{ "FileRequired", "File Required." },
		{ "InvalidFileFormat", "Invalid File Format." },
		{ "ImportCompleted", "Import Completed." },
		{ "codeIsRequired", "Code is Required." },
		{ "thisBrandHasTerminalsAndCannotBeDeleted", "This brand has terminals and cannot be deleted." },
		{ "thisBrokerHasTerminalsAndCannotBeDeleted", "This broker has terminals and cannot be deleted." },
		{ "accountNotFoundPleaseCheckYourDetails", "Account not found. Please check your details." },
		{ "accountNotFound", "Account not found." },
		{ "walletNotFound", "Wallet Not Found." },
		{ "processNotFound", "Process Not Found." },
		{ "aRelatedRecordWasNotFound", "A related record was not found." },

		// ===== Authentication & Authorization =====
		{ "pleaseSignInToContinue", "Please sign in to continue." },
		{ "loginInformationIsWrong", "Login Information is Wrong" },
		{ "invalidAPIKey", "Invalid API key" },
		{ "tooManyOTPRequestsPleaseWaitAndTryAgain", "Too many OTP requests. Please wait and try again." },
		{ "tooManyFailedAttemptsPleaseTryAgainLater", "Too many failed attempts. Please try again later." },
		{ "enteredOtpIsNotValidOrExpiredPleaseTryAgain", "Entered Otp is not Valid or Expired, Please try again." },
		{ "refreshTokenRequired", "Refresh Token Required." },
		{ "authTokenIsExpired", "Auth Token is Expired." },
		{ "yourSessionHasExpiredPleaseSignInAgain", "Your session has expired. Please sign in again." },

		// ===== Success =====
		{ "addressDeletedSuccessfully", "Address Deleted Successfully" },
		{ "addressUpdatedSuccessfully", "Address Updated Successfully" },
		{ "youAreNowFollowing", "You are now following " },
		{ "productRemovedSuccessfully", "Product removed successfully." },
		{ "transferMoneySuccessful", "Transfer Money Successful" },
		{ "youAreNoLongerFollowing", "You are no longer following " },
		{ "accountDeletedSuccessfully", "Account deleted successfully." },
		{ "yourDetailSubmittedSuccessfully", "Your Detail Submitted Successfully." },
		{ "processCompleted", "Process Completed." },

		// ===== Business Logic =====
		{ "addressWithThisZipCodeAlreadyExists", "Address with this ZipCode already exists." },
		{ "alreadyBookmarked", "Already Bookmarked" },
		{ "alreadyFollowingUser", "Already Following User" },
		{ "atLeastOneUserRequired", "At Least One User Required" },
		{ "yourBalanceIsNotEnough", "Your Balance is Not Enough." },
		{ "wrongDateSelected", "Wrong Date Selected" },
		{ "cannotFollowYourself", "Cannot Follow Yourself" },
		{ "futureDateSelected", "Future Date Selected" },
		{ "noCachedResultYetPleaseConfirmPaymentToFetchFreshData", "No cached result yet, please confirm payment to fetch fresh data." },
		{ "theSelectedChargeAmountIsNotOfferedByThisOperator", "The selected charge amount is not offered by this operator." },
		{ "licencePlateCantBeMoreThan10Characters", "Licence Plate can't be more than 10 Characters." },
		{ "nationalCodeIsNotMatchWithPhoneNumberOwner", "National Code is not Match with Phone Number Owner." },
		{ "passwordMustBeAtLeast6Characters", "Password must be at least 6 characters." },
		{ "couldNotDeleteProductPleaseTryLater", "Could not delete product. Please try later." },
		{ "shahkarIsNotAvailableAtThisTimePleaseTryAgainLater", "Shahkar is not Available at this Time, Please try again Later." },
		{ "accountAlreadyExistsWouldYouLikeToLogIn", "Account already exists. Would you like to log in?" },
		{ "userAlreadyHasWallet", "User Already has Wallet." },
		{ "zipCodeMustBe10CharactersLong", "Zip Code must be 10 Characters Long." },

		// ===== System / API =====
		{ "internalServerError", "Internal server error" },
		{ "paymentGatewayErrorPleaseTryAgain", "Payment gateway error. Please try again." },
		{ "transactionNotFound", "Transaction not found." },
		{ "invalidBase64RequestBody", "Invalid base64 request body" },
		{ "invalidJSONBody", "Invalid JSON body" },
		{ "invalidRequestFormat", "Invalid request format" },
		{ "requestTooLarge", "Request too large" },
		{ "securityError", "Security Error." },
		{ "systemError", "System Error" },
		{ "thirdPartyServiceError", "Third Party Service Error." },
		{ "youDoNotHaveClearanceToDoThisAction", "You Do Not have Clearance to do this Action." },
		{ "aRequiredFieldIsMissing", "A required field is missing." },
		{ "oneOfTheSubmittedValuesIsInvalid", "One of the submitted values is invalid." },
		{ "oneOfTheSubmittedValuesIsTooLong", "One of the submitted values is too long." },
		{ "thisRecordWasModifiedByAnotherOperationPleaseRetry", "This record was modified by another operation. Please retry." },
		{ "thisFileTypeIsNotSupported", "This file type is not supported." },
		{ "nameIsRequired", "Name is Required." },
		{ "pathIsRequired", "Path is Required." },
		{ "theRequestedPathIsInvalid", "The requested path is invalid." },
		{ "theRequestedPathWasNotFound", "The requested path was not found." },
		{ "anItemWithThisNameAlreadyExists", "An item with this name already exists." },
		{ "updatedSuccessfully", "Updated successfully." },
		{ "createdSuccessfully", "Created successfully." },
		{ "deletedSuccessfully", "Deleted successfully." },
		{ "notFound", "Not found." },
		{ "tableIsRequired", "Table is required." },
		{ "sqlIsRequired", "SQL is required." },
		{ "primaryKeyIsRequired", "Primary key is required." },
		{ "noValuesProvidedToWrite", "No values provided to write." },
		{ "validationFailedPleaseCheckYourInput", "Validation failed. Please check your input." },
		{ "failedToGenerateTheAgreementPleaseTryAgainLater", "Failed to generate the agreement. Please try again later." },
		{ "invalidStep", "Invalid step." },

		// ===== Not Found (additional) =====
		{ "contractNotFound", "Contract Not Found." },
		{ "dormNotFound", "Dorm Not Found." },
		{ "organizationNotFound", "Organization Not Found." },
		{ "settlementNotFound", "Settlement request not found." },
		{ "thisContractIsAlreadySettled", "This contract is already settled." },
		{ "theNewEndDateMustBeAfterTheCurrentOne", "The new end date must be after the current one." },
		{ "contractSettled", "Contract settled" },
		{ "dormDepositRefund", "Dorm deposit refund" },
		{ "invoiceDueSoon", "An invoice is due soon" },
		{ "invoiceIsOverdue", "An invoice is overdue" },
		{ "organizationSettlement", "Organization settlement" },
		{ "bedsOfAnotherOrganization", "The new bed belongs to another organization." },
		{ "onlyUnpaidInvoicesCanBeSplit", "Only an unpaid invoice can be split." },
		{ "selectACashOrBankAccount", "Select a cash box or bank account." },
		{ "accountCodeExists", "An account with this code already exists." },
		{ "accountHasEntries", "This account has entries or is a system account, so it cannot be deleted." },
		{ "ledgerAccountNotFound", "Account not found." },
		{ "voucherIsNotBalanced", "Total debit and total credit must be equal." },
		{ "voucherNotFound", "Voucher not found." },
		{ "onlyManualVouchersCanBeDeleted", "Only manual vouchers can be deleted." },
		{ "checkNotFound", "Check not found." },
		{ "checkIsNotPending", "Only a pending check can change status." },
		{ "checkIsDueSoon", "A check is due soon" },
		{ "dormBedInvoiceIssued", "Dorm invoice issued" },
		{ "hotelInvoiceIssued", "Hotel invoice issued" },
		{ "invoiceReceipt", "Invoice payment received" },
		{ "receivedCheck", "Received check" },
		{ "issuedCheck", "Issued check" },
		{ "checkCleared", "Check cleared" },
		{ "checkBounced", "Check bounced" },
		{ "checkReturned", "Check returned" },
		{ "platformCommission", "Platform commission" },
		{ "dormRoomNotFound", "Dorm Room Not Found." },
		{ "dormBedNotFound", "Dorm Bed Not Found." },
		{ "hotelNotFound", "Hotel Not Found." },
		{ "hotelRoomNotFound", "Hotel Room Not Found." },
		{ "invoiceNotFound", "Invoice Not Found." },
		{ "mediaNotFound", "Media Not Found." },
		{ "notificationNotFound", "Notification Not Found." },
		{ "parkingNotFound", "Parking Not Found." },
		{ "parkingTariffNotFound", "Parking Tariff Not Found." },
		{ "parkingSubscriptionNotFound", "Parking Subscription Not Found." },
		{ "plateRecordNotFound", "Plate Record Not Found." },
		{ "parkingStaffMemberNotFound", "Parking Staff Member Not Found." },
		{ "parkingShiftNotFound", "Parking Shift Not Found." },
		{ "thisEntryHasAlreadyBeenClosed", "This Entry Has Already Been Closed." },
		{ "thisVehicleIsAlreadyInsideTheParking", "This Vehicle Is Already Inside The Parking." },
		{ "parkingReportNotFound", "Parking Report Not Found." },
		{ "thisUsernameIsAlreadyTaken", "This username is already taken." },
		{ "receiverWalletNotFound", "Receiver Wallet Not Found." },
		{ "simCardNotFound", "Sim Card Not Found." },
		{ "vehicleNotFound", "Vehicle Not Found." },
		{ "logEntryNotFound", "Log entry not found." },
		{ "blogPostNotFound", "Blog post not found." },
		{ "blogPostRemovedSuccessfully", "Blog post removed successfully." },

		// ===== Business Logic (additional) =====
		{ "thisBedHasAnActiveContract", "This bed has an active contract." },
		{ "reservationNotFound", "Reservation Not Found." },
		{ "thisRoomIsNotAvailableForBooking", "This room is not available for booking." },
		{ "thisRoomIsAlreadyBookedForTheSelectedDates", "This room is already booked for the selected dates." },
		{ "checkOutDateMustBeAfterTheCheckInDate", "Check-out date must be after the check-in date." },
		{ "checkInDateIsRequired", "Check-in Date is Required." },
		{ "checkOutDateIsRequired", "Check-out Date is Required." },
		{ "guestCountIsRequired", "Guest Count is Required." },
		{ "reservationIsRequired", "Reservation is Required." },
		{ "roomIsRequired", "Room is Required." },
		{ "thisHotelIsCurrentlyNotAcceptingReservations", "This hotel is currently not accepting reservations." },
		{ "theCheckInDateCannotBeInThePast", "The check-in date cannot be in the past." },
		{ "theNumberOfGuestsIsMoreThanThisRoomCanTake", "The number of guests is more than this room can take." },
		{ "thisReservationHasAlreadyBeenCancelled", "This reservation has already been cancelled." },
		{ "aReservationThatHasAlreadyBeenCheckedInCannotBeCancelled", "A reservation that has already been checked in cannot be cancelled." },
		{ "theReservationWasCancelled", "The reservation was cancelled." },
		{ "thisInvoiceHasAlreadyBeenPaid", "This invoice has already been paid." },
		{ "paymentCompleted", "Payment completed." },
		{ "reservationRegistered", "Reservation registered" },
		{ "reservationConfirmed", "Reservation confirmed" },
		{ "reservationCancelled", "Reservation cancelled" },
		{ "hotelReservationPayment", "Hotel reservation payment" },
		{ "hotelReservationRefund", "Hotel reservation refund" },
		{ "dormInvoicePayment", "Dorm invoice payment" },
		{ "invoicePaid", "Invoice paid" },
		{ "newInvoicesIssued", "New invoices issued" },
		{ "thisMerchantAlreadyExists", "This merchant already exists." },
		{ "merchantCreationFeeIsRequired", "Merchant creation fee is required." },

		// ===== Success (additional) =====
		{ "bankAccountDeletedSuccessfully", "Bank Account deleted successfully." },
		{ "verificationCodeSent", "Verification code sent." },
		{ "vehicleCreatedSuccessfully", "Vehicle created successfully." },

		// Not Sorted
		{ "userIdentityVerificationIsNotCompleted", "User identity verification is not completed." },
		{ "terminalIsAlreadyAssignedToAMerchant", "Terminal is already assigned to a merchant." },
		{ "merchantIsAlreadyRegisteredWithAvreen", "Merchant is already registered with Avreen." },
		{ "userElectronicSignatureIsMissing", "User electronic signature is missing." },
		{ "failedToRegisterMerchantInAvreen", "Failed to register merchant in Avreen." },
		{ "merchantRegistrationSucceededButMerchantIdentifierWasNotReturnedByAvreen", "Merchant registration succeeded but merchant identifier was not returned by Avreen." },
		{ "failedToBindTerminalToMerchantInAvreen", "Failed to bind terminal to merchant in Avreen." },
		{ "youHaveToAcceptTheAgreementToContinue", "You have to accept the agreement to continue." },
		{ "generatingTheAgreementFailed", "Generating the agreement failed." },
		{ "thisTerminalRequestIsWaitingForApproval", "This terminal request is waiting for approval." },
		{ "thisTerminalRequestIsAlreadyApproved", "This terminal request is already approved." },
		{ "thisTerminalRequestIsNotWaitingForApproval", "This terminal request is not waiting for approval." },
		{ "yourRequestHasBeenSubmittedAndIsAwaitingApproval", "Your request has been submitted and is awaiting approval." },
		{ "anUnexpectedErrorOccurredPleaseTryAgainLater", "An unexpected error occurred. Please try again later." },

		// ===== Moadi =====
		{ "nameIsNotValid", "Name is not valid." },
		{ "economicCodeIsRequired", "Economic Code is Required." },
		{ "economicCodeIsNotValid", "Economic Code is not valid." },
		{ "legalEntityIsRequired", "Legal Entity is Required." },
		{ "legalEntityIsNotValid", "Legal Entity is not valid." },
		{ "uniqueTaxCodeIsRequired", "Unique Tax Code is Required." },
		{ "uniqueTaxCodeIsNotValid", "Unique Tax Code is not valid." },
		{ "ownerMobileIsRequired", "Owner Mobile is Required." },
		{ "ownerMobileIsNotValid", "Owner Mobile is not valid." },
		{ "ownerNationalCodeIsRequired", "Owner National Code is Required." },
		{ "ownerNationalCodeIsNotValid", "Owner National Code is not valid." },
		{ "taxpayerRequestNotFound", "Taxpayer request not found." },
		{ "thisTaxpayerRequestIsAlreadyApproved", "This taxpayer request is already approved." },
		{ "aTaxpayerWithThisEconomicCodeAlreadyExists", "A taxpayer with this economic code already exists." },
		{ "taxpayerRegistrationInNamatSystemFailed", "Taxpayer registration in Namat system failed." },
		// ===== Gold =====
		{ "idempotencyKeyIsRequired", "Idempotency key is required." },
		{ "idempotencyKeyIsNotValid", "Idempotency key is not valid." },
		{ "orderSideIsRequired", "Order side is required." },
		{ "atLeastOneScopeIsRequired", "At least one scope is required." },
		{ "sendExactlyOneOfBaseAmountOrQuoteAmountGreaterThanZero", "Send exactly one of base amount or quote amount, greater than zero." },
		{ "theGoldProviderIsNotConfigured", "The gold provider is not configured." },
		{ "theGoldProviderIsNotReachableRightNow", "The gold provider is not reachable right now." },
		{ "theGoldProviderReturnedAnUnexpectedError", "The gold provider returned an unexpected error." },
		{ "theGoldProviderRejectedTheRequestData", "The gold provider rejected the request data." },
		{ "thePaginationCursorIsInvalidOrExpiredStartFromTheFirstPage", "The pagination cursor is invalid or expired. Start from the first page." },
		{ "theRequestedGoldResourceWasNotFound", "The requested gold resource was not found." },
		{ "authenticationWithTheGoldProviderIsRequired", "Authentication with the gold provider is required." },
		{ "theGoldProviderCredentialsAreInvalid", "The gold provider credentials are invalid." },
		{ "theGoldProviderTokenIsInvalidOrExpired", "The gold provider token is invalid or expired." },
		{ "accessToThisGoldResourceIsDenied", "Access to this gold resource is denied." },
		{ "thisIPAddressIsNotAllowedByTheGoldProvider", "This IP address is not allowed by the gold provider." },
		{ "theGoldProviderClientAccountIsInactive", "The gold provider client account is inactive." },
		{ "theGoldProviderTokenWasNotFound", "The gold provider token was not found." },
		{ "theMaximumNumberOfActiveGoldTokensHasBeenReachedRevokeOneFirst", "The maximum number of active gold tokens has been reached. Revoke one first." },
		{ "theTokenIPWhitelistMustBeASubsetOfTheClientIPWhitelist", "The token IP whitelist must be a subset of the client IP whitelist." },
		{ "tooManyRequestsToTheGoldProviderPleaseTryAgainShortly", "Too many requests to the gold provider. Please try again shortly." },
		{ "tooManyFailedAuthenticationAttemptsPleaseTryAgainShortly", "Too many failed authentication attempts. Please try again shortly." },
		{ "yourGoldBusinessAccountIsSuspended", "Your gold business account is suspended." },
		{ "thisTradePairIsNotSupported", "This trade pair is not supported." },
		{ "theAssetPairDoesNotMatchTheRequest", "The asset pair does not match the request." },
		{ "theAssetWasNotFoundOrIsInactive", "The asset was not found or is inactive." },
		{ "theTradeRequestIsNotValid", "The trade request is not valid." },
		{ "theTradeAmountIsNotValid", "The trade amount is not valid." },
		{ "theAmountHasMoreDecimalPlacesThanTheAssetAllows", "The amount has more decimal places than the asset allows." },
		{ "theAmountIsBelowTheMinimumTradeSize", "The amount is below the minimum trade size." },
		{ "thisIdempotencyKeyHasAlreadyBeenUsedGenerateANewOneForEachOrder", "This idempotency key has already been used. Generate a new one for each order." },
		{ "yourOrderVolumeHasReachedTheLimitForTheCurrentTimeWindow", "Your order volume has reached the limit for the current time window." },
		{ "theOrderWasNotFound", "The order was not found." },
		{ "yourGoldWalletBalanceIsNotEnough", "Your gold wallet balance is not enough." },
		{ "theGoldPriceIsNotAvailableRightNowPleaseTryAgainShortly", "The gold price is not available right now. Please try again shortly." },
		{ "yourGoldBalanceIsNotEnoughForThisOrder", "Your gold balance is not enough for this order." },
		{ "yourGoldWalletIsLocked", "Your gold wallet is locked." },
		{ "theGoldTransactionWasNotFound", "The gold transaction was not found." },
		{ "theGoldOrderWasNotCompletedAnyReservedAmountHasBeenReturned", "The gold order was not completed. Any reserved amount has been returned." },
		{ "theGoldOrderIsBeingProcessedAndWillBeSettledShortly", "The gold order is being processed and will be settled shortly." },
		{ "theGoldServiceIsTemporarilyUnavailablePleaseTryAgainLater", "The gold service is temporarily unavailable. Please try again later." },
		{ "buyingGoldIsClosedRightNow", "Buying gold is not possible right now. Please try again later." },
		{ "sellingGoldIsClosedRightNow", "Selling gold is not possible right now. Please try again later." },
		{ "goldTradingIsClosedOnThisSideRightNow", "Trading on this side is not possible right now." },
		{ "aRequestedGoldScopeIsNotEnabledForThisAccount", "At least one requested gold scope is not enabled for this account." },
		{ "theGoldProviderWalletIsLocked", "The gold provider wallet is locked." },
		{ "theGoldProviderAccountBalanceIsNotEnough", "The gold provider business account balance is not enough." },

		// ===== Bill =====
		{ "billIdLengthMustBeBetween6And13Digits", "Bill Id length must be between 6 and 13 digits." },
		{ "paymentIdLengthMustBeBetween6And13Digits", "Payment Id length must be between 6 and 13 digits." },
		{ "billIdMustContainDigitsOnly", "Bill Id must contain digits only." },
		{ "paymentIdMustContainDigitsOnly", "Payment Id must contain digits only." },
		{ "billIdCheckDigitIsNotValid", "Bill Id check digit is not valid." },
		{ "paymentIdFirstControlDigitIsNotValid", "Payment Id first control digit is not valid." },
		{ "paymentIdSecondControlDigitIsNotValid", "Payment Id second control digit is not valid." },
		{ "companyCodeIsUnknown", "Company code is unknown." },
		{ "serviceTypeCodeIsUnknown", "Service type code is unknown." },
		{ "billInformationCouldNotBeParsed", "Bill information could not be parsed." },
		{ "theBillIsNotValid", "The bill is not valid." },
		{ "theBillAmountIsNotAvailable", "The bill amount is not available." },
		{ "topUpTypeIsRequired", "Top Up Type is Required." },
		{ "thisOperatorIsNotSupportedForDirectTopUp", "This operator is not supported for direct top up." },
		{ "theSumOfMultiplexedAmountsMustBeEqualToTheTotalAmount", "The sum of multiplexed amounts must be equal to the total amount." },
		{ "thisPaymentTypeIsNotSupportedByTheGateway", "This payment type is not supported by the gateway." },

		// ===== Validation (previously missing) =====
		{ "BedIdRequired", "Bed is Required." },
		{ "CapacityRequired", "Capacity is Required." },
		{ "CityMinLength", "City must be between 2 and 100 characters." },
		{ "CityRequired", "City is Required." },
		{ "ContractIdRequired", "Contract is Required." },
		{ "DepositRequired", "Deposit is Required." },
		{ "DormIdRequired", "Dorm is Required." },
		{ "DrivingLicenceNumberInvalid", "Driving Licence Number is Invalid." },
		{ "DrivingLicenceNumberRequired", "Driving Licence Number is Required." },
		{ "HotelIdRequired", "Hotel is Required." },
		{ "MonthlyRentRequired", "Monthly Rent is Required." },
		{ "NationalCodeNotValid", "National Code is Invalid." },
		{ "PricePerNightRequired", "Price Per Night is Required." },
		{ "TitleMaxLength", "Title is too long." },
		{ "TitleMinLength", "Title must be between 2 and 100 characters." },
		{ "UsersRequired", "Users are Required." },
		{ "passwordLengthMustBeBetween4And100Characters", "Password must be between 4 and 100 characters." },
		{ "amountIsNotValid", "Amount is not valid." },
		{ "TicketNotFound", "Ticket not found." },

		// ===== Charge / Internet package =====
		{ "chargeServiceIsNotAvailable", "The charge and internet package service is not available right now. Please try again in a few minutes." },
		{ "yourPreviousPurchaseIsStillInProgress", "Your previous purchase is still in progress. Please wait a moment." },
		{ "theMobileNumberIsNotValid", "The mobile number is not valid." },
		{ "theSelectedInternetPackageIsNoLongerAvailable", "The selected internet package is no longer available. Please open the package list again." },
		{ "thePriceOfThisItemHasChangedPleaseTryAgain", "The price of this item has changed. Please try again." },
		{ "chargePinPurchasedSuccessfully", "The charge PIN was purchased successfully." },
		{ "simCardChargedSuccessfully", "The SIM card was charged successfully." },
		{ "internetPackageActivatedSuccessfully", "The internet package was activated successfully." },
		{ "yourTransactionIsBeingProcessed", "Your transaction is being processed. The result will be known in a few minutes; if it fails, the amount is returned to your wallet." },

		// ===== Google login / password reset =====
		{ "googleSignInIsNotConfigured", "Sign in with Google is not available." },
		{ "googleTokenIsInvalid", "Google sign-in failed. Please try again." },
		{ "googleEmailIsNotVerified", "Your Google email is not verified." },
		{ "ifAnAccountExistsAResetCodeWasSent", "If an account exists for this email, a reset code has been sent to it." },
		{ "passwordResetCodeIsInvalidOrExpired", "The reset code is invalid or has expired." },
		{ "passwordChangedSuccessfully", "Your password has been changed." },
		{ "passwordResetEmailSubject", "Your password reset code" },
		{ "passwordResetEmailBody", "Your password reset code is {0}. It expires in {1} minutes. If you did not request it, ignore this email." },

		// ===== Sport =====
		{ "sportNotFound", "Sport not found." },
		{ "sportIsRequired", "Sport is required." },
		{ "sportTypeIsRequired", "Exactly one sport type is required." },
		{ "thisSportAlreadyExists", "This sport already exists." },
		{ "levelIsOutOfRange", "The level is out of the allowed range." },
		{ "thisSportIsAlreadyInYourProfile", "This sport is already in your profile." },
		{ "playerSportProfileNotFound", "Sport profile not found." },
		{ "sportIsInUseDisableItInstead", "This sport is used by players; disable it instead of deleting." },

		// ===== Tournament =====
		{ "tournamentNotFound", "Tournament not found." },
		{ "formatIsRequired", "Choose one tournament format." },
		{ "thisFormatIsNotAvailableYet", "This format is not available yet." },
		{ "participantTypeIsRequired", "Choose singles or doubles." },
		{ "capacityMustBeAtLeastTwo", "Capacity must be at least 2." },
		{ "registrationIsClosed", "Registration for this tournament is closed." },
		{ "tournamentIsFull", "This tournament is full." },
		{ "partnerEmailIsRequired", "Enter your partner's email." },
		{ "partnerNotFound", "No player was found with this email." },
		{ "aPlayerIsAlreadyRegistered", "A player is already registered in this tournament." },
		{ "addThisSportToYourProfileFirst", "Add this sport to your profile first." },
		{ "levelIsNotInTheTournamentRange", "Your level is not in this tournament's range." },
		{ "entryNotFound", "Entry not found." },
		{ "atLeastTwoApprovedEntriesAreRequired", "At least two approved entries are required." },
		{ "tournamentHasStarted", "The tournament has already started." },
		{ "matchNotFound", "Match not found." },
		{ "scoresAreInvalid", "The scores are invalid." },
		{ "thisFormatIsForIndividualPlayers", "This format is for individual players." },
		{ "teamNameIsRequired", "Enter the team name." },
		{ "playersMustBeAMultipleOfFour", "The number of players must be a multiple of 4." },
		{ "notEnoughEntriesForThisFormat", "There are not enough approved entries for this format." },
		{ "tournamentHasNotStarted", "The tournament hasn't started yet." },
		{ "matchIsNotReady", "Both sides of this match aren't known yet." },
		{ "aLaterMatchIsAlreadyPlayed", "A later match already depends on this result." },
		{ "scoresMustAddUpToPointsPerMatch", "The two scores must add up to the points per match." },
		{ "matchIsNotComplete", "The match isn't complete." },
		{ "invalidSetScore", "A set score isn't valid for this sport." },
		{ "drawsAreNotAllowedInKnockout", "A knockout match needs a winner." },
		{ "onlyAFinishedBoxLeagueCanContinue", "Only a finished box league can continue to a next period." },
		{ "aFinishedGameCannotBeDeleted", "A finished game can't be removed." },
		{ "achievementNotFound", "Achievement not found." },
		{ "bookingNotFound", "Booking not found." },
		{ "conversationNotFound", "Conversation not found." },
		{ "courtHasBookingsDeactivateItInstead", "This court has bookings; deactivate it instead." },
		{ "courtNotFound", "Court not found." },
		{ "durationIsNotValid", "The duration doesn't fit the court's time slots." },
		{ "gameNotFound", "Game not found." },
		{ "levelIsNotInTheGameRange", "Your level is not in this game's range." },
		{ "locationIsNotValid", "The location is not valid." },
		{ "messageNotFound", "Message not found." },
		{ "postNotFound", "Post not found." },
		{ "priceOrSlotIsNotValid", "The price or the slot length is not valid." },
		{ "reportNotFound", "Report not found." },
		{ "reportTypeIsRequired", "Choose what you are reporting." },
		{ "teamsAreNotValid", "Both teams must be players of this game, nobody on both sides." },
		{ "textIsRequired", "Text is required." },
		{ "textIsTooLong", "The text is too long." },
		{ "thanksForYourReport", "Thanks, we'll review your report." },
		{ "theGameHasNotStartedYet", "The game hasn't started yet." },
		{ "theOrganizerCannotLeaveCancelInstead", "The organizer can't leave; cancel the game instead." },
		{ "theStartTimeIsInThePast", "The start time is in the past." },
		{ "theVenueIsClosedAtThisTime", "The venue is closed at this time." },
		{ "thisBookingCannotBeCancelled", "This booking can't be cancelled." },
		{ "thisBookingIsCancelled", "This booking is cancelled." },
		{ "thisGameIsFull", "This game is full or closed." },
		{ "thisTimeIsAlreadyBooked", "This time is already booked." },
		{ "thisVenueHasUpcomingBookings", "This venue has upcoming bookings." },
		{ "thisVenueIsNotTakingBookings", "This venue is not taking bookings." },
		{ "thisVenueOnlyTakesOnlinePayment", "This venue only takes online payment." },
		{ "tournamentEntryFee", "Tournament entry fee" },
		{ "tournamentEntryFees", "Tournament entry fees" },
		{ "tournamentEntryRefund", "Tournament entry fee refund" },
		{ "courtBookingPayment", "Court booking" },
		{ "courtBookingRefund", "Court booking refund" },
		{ "courtBookingSettlement", "Court booking payout" },
		{ "userNotFound", "User not found." },
		{ "venueNotFound", "Venue not found." },
		{ "youCannotBlockYourself", "You can't block yourself." },
		{ "youCannotMessageThisUser", "You can't message this user." },
		{ "youHaveAlreadyJoined", "You have already joined or asked to join." },
		{ "yourShareIsAlreadyPaid", "Your share is already paid." },
		// ===== Phases 5-8 =====
		{ "address", "Address" },
		{ "amount", "Amount" },
		{ "capacityIsFull", "Capacity is full." },
		{ "checkIn", "Check-in" },
		{ "checkOut", "Check-out" },
		{ "codeAlreadyExists", "This code already exists." },
		{ "deposit", "Deposit" },
		{ "description", "Description" },
		{ "discount", "Discount" },
		{ "dorm", "Dorm" },
		{ "dormContractTitle", "Dorm Residence Contract" },
		{ "dueDate", "Due Date" },
		{ "emergencyContact", "Emergency Contact" },
		{ "endDate", "End Date" },
		{ "endDateMustBeAfterStartDate", "The end date must be after the start date." },
		{ "extraCharge", "Extra charge" },
		{ "guardian", "Guardian" },
		{ "guest", "Guest" },
		{ "guestFolio", "Guest Folio" },
		{ "vatIncluded", "VAT included" },
		{ "planNotFound", "Plan not found." },
		{ "planModulesRequired", "Choose at least one system for the plan." },
		{ "planPricesAreNotValid", "The plan period or price is not valid." },
		{ "trialNotAvailable", "The free trial is not available for this organization." },
		{ "subscriptionNotFound", "No unpaid subscription was found." },
		{ "subscription", "Subscription" },
		{ "subscriptionInactive", "This organization's subscription does not include this part or has expired." },
		{ "organization", "Organization" },
		{ "guestSignature", "Guest signature" },
		{ "guests", "Guests" },
		{ "handoverDamage", "Room handover damage" },
		{ "hotel", "Hotel" },
		{ "invoice", "Invoice" },
		{ "itemIsInUse", "This item is in use and cannot be deleted." },
		{ "itemNotFound", "Item not found." },
		{ "itemsAreRequired", "Add at least one item." },
		{ "lowStockAlert", "Low stock alert" },
		{ "minimumStayIsNotMet", "The minimum stay for these dates is not met." },
		{ "monthlyRent", "Monthly Rent" },
		{ "nationalCode", "National Code" },
		{ "newDormApplication", "New residence application" },
		{ "newLeaveRequest", "New night leave request" },
		{ "newMaintenanceRequest", "New maintenance request" },
		{ "newShiftAssigned", "A new shift is assigned to you" },
		{ "newTaskAssigned", "A new task is assigned to you" },
		{ "newVisitorRequest", "New visitor request" },
		{ "nights", "Nights" },
		{ "notEnoughStock", "Not enough stock in this warehouse." },
		{ "notPaid", "Not paid" },
		{ "organizationPlanExpired", "The organization's subscription has expired." },
		{ "organizationPlanLimitReached", "The organization's subscription limit is reached." },
		{ "organizationSignature", "Organization signature and stamp" },
		{ "paid", "Paid" },
		{ "paidAmount", "Paid" },
		{ "paymentReceipt", "Payment Receipt" },
		{ "penalty", "Penalty" },
		{ "phoneNumber", "Phone Number" },
		{ "purchase", "Purchase" },
		{ "purchaseIsNotApproved", "This purchase request is not approved yet." },
		{ "quantityIsNotValid", "Quantity is not valid." },
		{ "remaining", "Remaining" },
		{ "reservationCode", "Reservation Code" },
		{ "reservationExtended", "Your reservation is extended" },
		{ "reservationExtension", "Reservation extension" },
		{ "resident", "Resident" },
		{ "residentSignature", "Resident signature" },
		{ "room", "Room" },
		{ "roomAndBed", "Room / Bed" },
		{ "roomChangeDifference", "Room change difference" },
		{ "roomCharge", "Room charge" },
		{ "selectALaundryMachine", "Select a laundry machine." },
		{ "selectTheTargetWarehouse", "Select the target warehouse." },
		{ "shiftIsAlreadyClosed", "This shift is already closed." },
		{ "startDate", "Start Date" },
		{ "status", "Status" },
		{ "stockAdjustment", "Stock adjustment" },
		{ "stockIn", "Stock in" },
		{ "stockOut", "Stock out" },
		{ "thisMealIsPast", "This meal is in the past." },
		{ "thisRequestIsAlreadyReviewed", "This request is already reviewed." },
		{ "thisReservationCannotBeChanged", "This reservation cannot be changed." },
		{ "thisRoomIsClosedOnTheSelectedDates", "This room is closed on the selected dates." },
		{ "totalPrice", "Total Price" },
		{ "unitIsRequired", "Unit is required." },
		{ "violationRecorded", "A violation is recorded for you" },
		{ "warningRecorded", "A warning is recorded for you" },
		{ "youAlreadyHaveAnOpenApplication", "You already have an open application here." },
		{ "youAlreadyReservedThis", "You already reserved this." },
		{ "youCannotApplyToThisPlace", "You cannot apply to this place." },
		{ "youCannotBookThisPlace", "You cannot book this place." },
		{ "youHaveNoActiveContractHere", "You have no active contract here." },
		{ "yourRequestIsApproved", "Your request is approved" },
		{ "yourRequestIsDone", "Your request is done" },
		{ "yourRequestIsRejected", "Your request is rejected" },
		{ "dormApplicationApproved", "Your residence application is approved" },
		{ "dormApplicationRejected", "Your residence application is rejected" },
		{ "dormApplicationWaitlisted", "Your residence application is on the waiting list" },
		{ "dormApplicationUpdated", "Your residence application is updated" },
	};

	private static readonly Dictionary<string, string> Fa = new() {
		// ===== Required =====
		{ "addressIsRequired", "آدرس الزامی است" },
		{ "amountRequired", "مبلغ الزامی است" },
		{ "bankAccountIsRequired", "شماره حساب الزامی است" },
		{ "businessTitleIsRequired", "عنوان کسب و کار الزامی است." },
		{ "brandIsRequired", "برند الزامی است." },
		{ "brokerIsRequired", "کارگزار الزامی است." },
		{ "cityCodeIsRequired", "کد شهر الزامی است" },
		{ "commentIsRequired", "نظر الزامی است." },
		{ "dailyPriceRequired", "مبلغ روزانه الزامی است" },
		{ "dateIsRequired", "تاریخ الزامی است" },
		{ "descriptionIsRequired", "توضیحات الزامی است" },
		{ "emailIsRequired", "ایمیل الزامی است." },
		{ "endDateIsRequired", "تاریخ پایان الزامی است" },
		{ "entrancePriceRequired", "مبلغ ورودی الزامی است" },
		{ "firstNameIsRequired", "نام الزامی است" },
		{ "hourlyPriceRequired", "مبلغ ساعتی الزامی است" },
		{ "iBanIsRequired", "شماره شبا الزامی است." },
		{ "idIsRequired", "شناسه الزامی است" },
		{ "terminalIdIsRequired", "شناسه ترمینال الزامی است." },
		{ "landlineIsRequired", "شماره تلفن ثابت الزامی است" },
		{ "lastNameIsRequired", "نام خانوادگی الزامی است" },
		{ "licencePlateIsRequired", "شماره پلاک الزامی است." },
		{ "merchantNameIsRequired", "نام پذیرنده الزامیست." },
		{ "mccIsRequired", "کد صنف الزامی است" },
		{ "nationalCodeIsRequired", "کد ملی الزامی است" },
		{ "numberRequired", "شماره الزامی است" },
		{ "otpIsRequired", "کد تایید الزامی است" },
		{ "ownerNameIsRequired", "نام مالک فروشگاه الزامی است" },
		{ "ownerPhoneNumberIsRequired", "شماره تلفن مالک الزامی است." },
		{ "pleaseEnterAPassword", "لطفاً رمز عبور را وارد کنید." },
		{ "phoneNumberIsRequired", "شماره تلفن الزامی است." },
		{ "priceIsRequired", "قیمت الزامی است" },
		{ "productIsRequired", "محصول الزامی است." },
		{ "required", "مورد نیاز" },
		{ "serialIsRequired", "سریال الزامی است" },
		{ "startDateIsRequired", "تاریخ شروع الزامی است" },
		{ "subtitleIsRequired", "عنوان فرعی الزامی است" },
		{ "tagsIsRequired", "برچسب‌ها الزامی است" },
		{ "titleIsRequired", "عنوان الزامی است" },
		{ "trackingNumberRequired", "کد رهگیری الزامی است" },
		{ "userIsRequired", "کاربر الزامی است" },
		{ "userNameIsRequired", "نام کاربری الزامی است." },
		{ "zipCodeIsRequired", "کد پستی الزامی است." },
		{ "fatherNameRequired", "نام پدر الزامی است." },
		{ "birthDateRequired", "تاریخ تولد الزامی است." },
		{ "invalidDateFormat", "فرمت تاریخ صحیح نیست." },
		{ "nationalCardFrontRequired", "روی کارت ملی الزامی است." },
		{ "nationalCardBackRequired", "پشت کارت ملی الزامی است." },
		{ "birthCertificateFirstRequired", "صفحه اول شناسنامه الزامی است." },
		{ "visualAuthenticationRequired", "احراز هویت تصویری الزامی است." },
		{ "signatureRequired", "امضا الزامی است." },
		{ "billIdRequired",  "شناسه قبض الزامی است." },
		{ "paymentIdRequired",  "شناسه پرداخت الزامی است." },
		{ "modelIsRequired",  "مدل الزامی است." },
		{ "merchantIsRequired", "پذیرنده الزامی است." },

		// ===== Invalid =====
		{ "addressIsNotValid", "آدرس صحیح نیست." },
		{ "bankAccountIsNotValid", "شماره حساب صحیح نیست." },
		{ "businessTitleIsNotValid", "عنوان کسب و کار صحیح نیست." },
		{ "cityCodeIsNotValid", "کد شهر صحیح نیست." },
		{ "pleaseEnterAValidEmail", "لطفاً یک ایمیل معتبر وارد کنید." },
		{ "firstNameIsInvalid", "نام نامعتبر است" },
		{ "iBanIsInvalid", "شماره شبا اشتباه است." },
		{ "landlineIsNotValid", "شماره تلفن ثابت صحیح نیست." },
		{ "lastNameIsInvalid", "نام خانوادگی نامعتبر است" },
		{ "licencePlateIsInvalid", "شماره پلاک اشتباه است." },
		{ "merchantNameIsNotValid", "نام پذیرنده صحیح نیست." },
		{ "mccIsNotValid", "کد صنف صحیح نیست." },
		{ "nationalCodeIsInvalid", "کد ملی نامعتبر است" },
		{ "ownerNameIsNotValid", "نام مالک فروشگاه صحیح نیست" },
		{ "ownerPhoneNumberIsNotValid", "شماره تلفن مالک صحیح نیست." },
		{ "passwordMustBe6100Characters", "رمز عبور باید بین 6 تا 100 کاراکتر باشد." },
		{ "pleaseEnterAValidPhoneNumber", "لطفاً یک شماره تلفن معتبر وارد کنید." },
		{ "phoneNumberIsNotValid", "شماره تلفن معتبر نیست." },
		{ "usernameIsInvalidPleaseTryAnother", "نام کاربری نامعتبر است. لطفاً دیگری را امتحان کنید." },
		{ "userNameIsNotValid", "نام کاربری معتبر نیست." },
		{ "zipCodeIsInvalid", "کد پستی اشتباه است." },
		{ "zipCodeIsNotValid", "کد پستی صحیح نیست." },

		// ===== Duplicate =====
		{ "thisCodeAlreadyExists", "کد تکراری است." },
		{ "thisEmailAlreadyExists", "ایمیل تکراری است." },
		{ "thisIdAlreadyExists", "آیدی تکراری است." },
		{ "thisIMEIAlreadyExists", "IMEI تکراری است." },
		{ "thisNationalCodeAlreadyExists", "کد ملی تکراری است." },
		{ "thisPhoneNumberAlreadyExists", "شماره موبایل تکراری است." },
		{ "thisSimCardNumberAlreadyExists", "شماره سیمکارت تکراری است." },
		{ "thisSimCardSerialAlreadyExists", "سریال سیمکارت تکراری است." },
		{ "thisSlugAlreadyExists", "اسلاگ تکراری است." },
		{ "thisTerminalIdAlreadyExists", "شناسه ترمینال تکراری است." },
		{ "thisTrackingNumberAlreadyExists", "کد رهگیری تکراری است." },
		{ "thisNumberPlateAlreadyExists", "شماره پلاک تکراری است." },
		{ "thisUserNameAlreadyExists", "نام کاربری تکراری است." },
		{ "thisRecordAlreadyExists", "این رکورد از قبل وجود دارد." },

		// ===== Not Found =====
		{ "addressNotFound", "آدرس یافت نشد" },
		{ "bankAccountNotFound", "حساب بانکی یافت نشد." },
		{ "categoryNotFoundPleaseTryAnother", "دسته بندی یافت نشد. لطفاً دیگری را امتحان کنید." },
		{ "commentNotFound", "نظر یافت نشد." },
		{ "contentNotFound", "محتوا یافت نشد." },
		{ "contentUpdatedSuccessfully", "محتوا با موفقیت به‌روزرسانی شد." },
		{ "contentRemovedSuccessfully", "محتوا با موفقیت حذف شد." },
		{ "examNotFound", "آزمون یافت نشد." },
		{ "errorFindingTheRelation", "خطا در یافتن رابطه" },
		{ "productNotFoundPleaseCheckDetails", "محصول یافت نشد. لطفاً جزئیات را بررسی کنید." },
		{ "senderWalletNotFound", "کیف پول فرستنده یافت نشد" },
		{ "merchantNotFound", "پذیرنده یافت نشد." },
		{ "terminalNotFound", "ترمینال یافت نشد." },
		{ "terminalNotFoundCheckYourDetails", "ترمینال یافت نشد. لطفا اطلاعات خود را بررسی کنید." },
		{ "terminalBrandNotFound", "برند دستگاه یافت نشد." },
		{ "terminalBrokerNotFound", "کارگزار یافت نشد." },
		{ "terminalBrandIsRequired", "انتخاب برند دستگاه الزامی است" },
		{ "terminalBrokerIsRequired", "انتخاب کارگزار الزامی است" },
		{ "printTheAgreementSignItAndSendItByPost", "قرارداد را چاپ کنید، هر دو طرف آن را امضا کنند و سپس با پست ارسال نمایید." },
		{ "TitleRequired", "عنوان الزامی است." },
		{ "postalCodeIsRequired", "کدپستی الزامی است." },
		{ "registrationNumberIsRequired", "شماره ثبت الزامی است." },
		{ "representativeIsRequired", "نام نماینده الزامی است." },
		{ "signatureIsRequired", "امضا الزامی است." },
		{ "logoIsRequired", "لوگو الزامی است." },
		{ "ModelIsRequired", "مدل الزامی است." },
		{ "FileRequired", "فایل الزامی است." },
		{ "InvalidFileFormat", "فرمت فایل نامعتبر است." },
		{ "ImportCompleted", "درون‌ریزی انجام شد." },
		{ "codeIsRequired", "کد الزامی است." },
		{ "thisBrandHasTerminalsAndCannotBeDeleted", "این برند دارای ترمینال است و قابل حذف نیست." },
		{ "thisBrokerHasTerminalsAndCannotBeDeleted", "این کارگزار دارای ترمینال است و قابل حذف نیست." },
		{ "accountNotFoundPleaseCheckYourDetails", "کاربری با این اطلاعات یافت نشد. لطفاً اطلاعات خود را بررسی کنید." },
		{ "accountNotFound", "کاربر یافت نشد." },
		{ "walletNotFound", "کیف پول یافت نشد." },
		{ "processNotFound", "فرایند یافت نشد" },
		{ "aRelatedRecordWasNotFound", "رکورد مرتبط یافت نشد." },

		// ===== Authentication & Authorization =====
		{ "pleaseSignInToContinue", "لطفاً برای ادامه وارد شوید." },
		{ "loginInformationIsWrong", "اطلاعات ورود اشتباه است" },
		{ "invalidAPIKey", "کلید API نامعتبر است" },
		{ "tooManyOTPRequestsPleaseWaitAndTryAgain", "تعداد درخواست‌های کد تایید زیاد است. لطفاً صبر کرده و دوباره امتحان کنید." },
		{ "tooManyFailedAttemptsPleaseTryAgainLater", "تعداد تلاش‌های ناموفق زیاد است. لطفاً بعداً دوباره امتحان کنید." },
		{ "enteredOtpIsNotValidOrExpiredPleaseTryAgain", "کد تایید وارد شده صحیح نیست یا منقضی شده. لطفا دوباره امتحان کنید." },
		{ "refreshTokenRequired", "توکن الزامیست" },
		{ "authTokenIsExpired", "توکن احراز هویت منقضی شده است." },
		{ "yourSessionHasExpiredPleaseSignInAgain", "نشست شما منقضی شده است. لطفاً دوباره وارد شوید." },

		// ===== Success =====
		{ "addressDeletedSuccessfully", "آدرس با موفقیت حذف شد" },
		{ "addressUpdatedSuccessfully", "آدرس با موفقیت به روز شد" },
		{ "youAreNowFollowing", "شما اکنون در حال فالو کردن هستید، " },
		{ "productRemovedSuccessfully", "محصول با موفقیت حذف شد." },
		{ "transferMoneySuccessful", "انتقال پول با موفقیت انجام شد" },
		{ "youAreNoLongerFollowing", "شما دیگر فالو نمی‌کنید، " },
		{ "accountDeletedSuccessfully", "حساب کاربری با موفقیت حذف شد." },
		{ "yourDetailSubmittedSuccessfully", "جزئیات شما با موفقیت ارسال شد." },
		{ "processCompleted", "فرایند با موفقیت تکمیل شد" },

		// ===== Business Logic =====
		{ "addressWithThisZipCodeAlreadyExists", "آدرسی با این کد پستی از قبل وجود دارد." },
		{ "alreadyBookmarked", "از قبل بوکمارک شده است" },
		{ "alreadyFollowingUser", "از قبل این کاربر را فالو می‌کنید" },
		{ "atLeastOneUserRequired", "حداقل یک کاربر مورد نیاز است" },
		{ "yourBalanceIsNotEnough", "موجودی شما کافی نیست." },
		{ "wrongDateSelected", "تاریخ اشتباه انتخاب شده است" },
		{ "cannotFollowYourself", "امکان فالو کردن خودتان وجود ندارد" },
		{ "futureDateSelected", "تاریخ آینده انتخاب شده است" },
		{ "noCachedResultYetPleaseConfirmPaymentToFetchFreshData", "استعلام قبلی یافت نشد، برای دریافت اطلاعات جدید پرداخت را تأیید کنید." },
		{ "theSelectedChargeAmountIsNotOfferedByThisOperator", "مبلغ شارژ انتخاب‌شده برای این اپراتور معتبر نیست." },
		{ "licencePlateCantBeMoreThan10Characters", "طول پلاک خودرو نمیتواند بیشتر از ۱۰ کاراکتر باشد." },
		{ "nationalCodeIsNotMatchWithPhoneNumberOwner", "کد ملی با صاحب شماره تلفن مطابقت ندارد." },
		{ "passwordMustBeAtLeast6Characters", "رمز عبور باید حداقل 6 کاراکتر باشد." },
		{ "couldNotDeleteProductPleaseTryLater", "حذف محصول امکان پذیر نبود. لطفاً بعداً دوباره امتحان کنید." },
		{ "shahkarIsNotAvailableAtThisTimePleaseTryAgainLater", "شاهکار در این زمان در دسترس نیست، لطفاً بعداً دوباره امتحان کنید." },
		{ "accountAlreadyExistsWouldYouLikeToLogIn", "حساب کاربری از قبل وجود دارد. آیا مایل به ورود هستید؟" },
		{ "userAlreadyHasWallet", "کاربر از قبل کیف پول دارد." },
		{ "zipCodeMustBe10CharactersLong", "کد پستی باید 10 کاراکتر باشد." },

		// ===== System / API =====
		{ "internalServerError", "خطای داخلی سرور" },
		{ "paymentGatewayErrorPleaseTryAgain", "خطای درگاه پرداخت. لطفاً دوباره تلاش کنید." },
		{ "transactionNotFound", "تراکنش یافت نشد." },
		{ "invalidBase64RequestBody", "بدنه درخواست base64 نامعتبر است" },
		{ "invalidJSONBody", "بدنه JSON نامعتبر است" },
		{ "invalidRequestFormat", "قالب درخواست نامعتبر است" },
		{ "requestTooLarge", "درخواست بیش از حد بزرگ است" },
		{ "securityError", "خطای امنیتی" },
		{ "systemError", "خطای سیستم" },
		{ "thirdPartyServiceError", "خطای سامانه مرجع" },
		{ "youDoNotHaveClearanceToDoThisAction", "شما مجاز به انجام این عملیات نیستید." },
		{ "aRequiredFieldIsMissing", "یکی از فیلدهای الزامی وارد نشده است." },
		{ "oneOfTheSubmittedValuesIsInvalid", "یکی از مقادیر ارسال‌شده نامعتبر است." },
		{ "oneOfTheSubmittedValuesIsTooLong", "یکی از مقادیر ارسال‌شده بیش از حد طولانی است." },
		{ "thisRecordWasModifiedByAnotherOperationPleaseRetry", "این رکورد توسط عملیات دیگری تغییر کرده است. لطفاً دوباره تلاش کنید." },
		{ "thisFileTypeIsNotSupported", "این نوع فایل پشتیبانی نمی‌شود." },
		{ "pathIsRequired", "مسیر الزامی است." },
		{ "theRequestedPathIsInvalid", "مسیر درخواستی نامعتبر است." },
		{ "theRequestedPathWasNotFound", "مسیر درخواستی یافت نشد." },
		{ "anItemWithThisNameAlreadyExists", "موردی با این نام از قبل وجود دارد." },
		{ "updatedSuccessfully", "با موفقیت به‌روزرسانی شد." },
		{ "createdSuccessfully", "با موفقیت ایجاد شد." },
		{ "deletedSuccessfully", "با موفقیت حذف شد." },
		{ "notFound", "یافت نشد." },
		{ "tableIsRequired", "نام جدول الزامی است." },
		{ "sqlIsRequired", "دستور SQL الزامی است." },
		{ "primaryKeyIsRequired", "کلید اصلی الزامی است." },
		{ "noValuesProvidedToWrite", "هیچ مقداری برای ثبت ارائه نشده است." },
		{ "validationFailedPleaseCheckYourInput", "اعتبارسنجی ناموفق بود. لطفاً ورودی خود را بررسی کنید." },
		{ "failedToGenerateTheAgreementPleaseTryAgainLater", "ایجاد قرارداد با خطا مواجه شد. لطفاً بعداً دوباره تلاش کنید." },
		{ "invalidStep", "مرحله نامعتبر است." },

		// ===== Not Found (additional) =====
		{ "contractNotFound", "قرارداد یافت نشد." },
		{ "dormNotFound", "خوابگاه یافت نشد." },
		{ "organizationNotFound", "مجموعه یافت نشد." },
		{ "settlementNotFound", "درخواست تسویه یافت نشد." },
		{ "thisContractIsAlreadySettled", "این قرارداد قبلاً تسویه شده است." },
		{ "theNewEndDateMustBeAfterTheCurrentOne", "تاریخ پایان جدید باید بعد از تاریخ پایان فعلی باشد." },
		{ "contractSettled", "قرارداد تسویه شد" },
		{ "dormDepositRefund", "برگشت ودیعه‌ی خوابگاه" },
		{ "invoiceDueSoon", "سررسید قبض نزدیک است" },
		{ "invoiceIsOverdue", "مهلت پرداخت قبض گذشته است" },
		{ "organizationSettlement", "تسویه‌ی مجموعه" },
		{ "bedsOfAnotherOrganization", "تخت جدید متعلق به مجموعه‌ی دیگری است." },
		{ "onlyUnpaidInvoicesCanBeSplit", "فقط قبض پرداخت‌نشده را می‌توان تقسیط کرد." },
		{ "selectACashOrBankAccount", "یک صندوق یا حساب بانکی انتخاب کنید." },
		{ "accountCodeExists", "حسابی با این کد وجود دارد." },
		{ "accountHasEntries", "این حساب گردش دارد یا حساب سیستمی است و حذف نمی‌شود." },
		{ "ledgerAccountNotFound", "حساب یافت نشد." },
		{ "voucherIsNotBalanced", "جمع بدهکار و بستانکار باید برابر باشد." },
		{ "voucherNotFound", "سند یافت نشد." },
		{ "onlyManualVouchersCanBeDeleted", "فقط سندهای دستی حذف می‌شوند." },
		{ "checkNotFound", "چک یافت نشد." },
		{ "checkIsNotPending", "وضعیت فقط برای چک در جریان عوض می‌شود." },
		{ "checkIsDueSoon", "سررسید چک نزدیک است" },
		{ "dormBedInvoiceIssued", "صدور قبض خوابگاه" },
		{ "hotelInvoiceIssued", "صدور فاکتور هتل" },
		{ "invoiceReceipt", "دریافت وجه قبض" },
		{ "receivedCheck", "چک دریافتی" },
		{ "issuedCheck", "چک پرداختی" },
		{ "checkCleared", "وصول چک" },
		{ "checkBounced", "برگشت چک" },
		{ "checkReturned", "عودت چک" },
		{ "platformCommission", "کمیسیون سامانه" },
		{ "dormRoomNotFound", "اتاق خوابگاه یافت نشد." },
		{ "dormBedNotFound", "تخت خوابگاه یافت نشد." },
		{ "hotelNotFound", "هتل یافت نشد." },
		{ "hotelRoomNotFound", "اتاق هتل یافت نشد." },
		{ "invoiceNotFound", "فاکتور یافت نشد." },
		{ "mediaNotFound", "رسانه یافت نشد." },
		{ "notificationNotFound", "اعلان یافت نشد." },
		{ "parkingNotFound", "پارکینگ یافت نشد." },
		{ "parkingTariffNotFound", "تعرفه پارکینگ یافت نشد." },
		{ "parkingSubscriptionNotFound", "اشتراک یافت نشد." },
		{ "plateRecordNotFound", "رکورد پلاک یافت نشد." },
		{ "parkingStaffMemberNotFound", "کارمند پارکینگ یافت نشد." },
		{ "parkingShiftNotFound", "شیفت یافت نشد." },
		{ "thisEntryHasAlreadyBeenClosed", "خروج این خودرو قبلاً ثبت شده است." },
		{ "thisVehicleIsAlreadyInsideTheParking", "این خودرو هم‌اکنون داخل پارکینگ است." },
		{ "parkingReportNotFound", "گزارش پارکینگ یافت نشد." },
		{ "thisUsernameIsAlreadyTaken", "این نام کاربری قبلاً استفاده شده است." },
		{ "receiverWalletNotFound", "کیف پول گیرنده یافت نشد." },
		{ "simCardNotFound", "سیمکارت یافت نشد." },
		{ "vehicleNotFound", "خودرو یافت نشد." },
		{ "logEntryNotFound", "رکورد لاگ یافت نشد." },
		{ "blogPostNotFound", "پست وبلاگ یافت نشد." },
		{ "blogPostRemovedSuccessfully", "پست وبلاگ با موفقیت حذف شد." },

		// ===== Business Logic (additional) =====
		{ "thisBedHasAnActiveContract", "این تخت دارای قرارداد فعال است." },
		{ "reservationNotFound", "رزرو یافت نشد." },
		{ "thisRoomIsNotAvailableForBooking", "این اتاق برای رزرو در دسترس نیست." },
		{ "thisRoomIsAlreadyBookedForTheSelectedDates", "این اتاق در تاریخ‌های انتخاب‌شده قبلاً رزرو شده است." },
		{ "checkOutDateMustBeAfterTheCheckInDate", "تاریخ خروج باید بعد از تاریخ ورود باشد." },
		{ "checkInDateIsRequired", "تاریخ ورود الزامی است." },
		{ "checkOutDateIsRequired", "تاریخ خروج الزامی است." },
		{ "guestCountIsRequired", "تعداد مهمان الزامی است." },
		{ "reservationIsRequired", "رزرو الزامی است." },
		{ "roomIsRequired", "اتاق الزامی است." },
		{ "thisHotelIsCurrentlyNotAcceptingReservations", "این هتل در حال حاضر رزرو نمی‌پذیرد." },
		{ "theCheckInDateCannotBeInThePast", "تاریخ ورود نمی‌تواند در گذشته باشد." },
		{ "theNumberOfGuestsIsMoreThanThisRoomCanTake", "تعداد مهمان از ظرفیت این اتاق بیشتر است." },
		{ "thisReservationHasAlreadyBeenCancelled", "این رزرو قبلاً لغو شده است." },
		{ "aReservationThatHasAlreadyBeenCheckedInCannotBeCancelled", "رزروی که پذیرش شده است قابل لغو نیست." },
		{ "theReservationWasCancelled", "رزرو لغو شد." },
		{ "thisInvoiceHasAlreadyBeenPaid", "این فاکتور قبلاً پرداخت شده است." },
		{ "paymentCompleted", "پرداخت انجام شد." },
		{ "reservationRegistered", "رزرو ثبت شد" },
		{ "reservationConfirmed", "رزرو تایید شد" },
		{ "reservationCancelled", "رزرو لغو شد" },
		{ "hotelReservationPayment", "پرداخت رزرو هتل" },
		{ "hotelReservationRefund", "استرداد وجه رزرو هتل" },
		{ "dormInvoicePayment", "پرداخت فاکتور خوابگاه" },
		{ "invoicePaid", "فاکتور پرداخت شد" },
		{ "newInvoicesIssued", "فاکتورهای جدید صادر شد" },
		{ "nameIsRequired", "نام الزامی است." },
		{ "thisMerchantAlreadyExists", "این پذیرنده از قبل وجود دارد." },
		{ "merchantCreationFeeIsRequired", "پرداخت هزینه ایجاد پذیرنده الزامی است." },

		// ===== Success (additional) =====
		{ "bankAccountDeletedSuccessfully", "حساب بانکی با موفقیت حذف شد." },
		{ "verificationCodeSent", "کد تایید ارسال شد." },
		{ "vehicleCreatedSuccessfully", "خودرو با موفقیت ایجاد شد." },

		// Not Sorted
		{ "userIdentityVerificationIsNotCompleted", "احراز هویت کاربر به طور کامل تأیید نشده است." },
		{ "terminalIsAlreadyAssignedToAMerchant", "این ترمینال قبلاً به یک پذیرنده اختصاص داده شده است." },
		{ "merchantIsAlreadyRegisteredWithAvreen", "این پذیرنده قبلاً در آورین ثبت شده است." },
		{ "userElectronicSignatureIsMissing", "امضای الکترونیکی کاربر ثبت نشده است." },
		{ "failedToRegisterMerchantInAvreen", "ثبت پذیرنده در سامانه آورین با خطا مواجه شد." },
		{ "merchantRegistrationSucceededButMerchantIdentifierWasNotReturnedByAvreen", "ثبت پذیرنده انجام شد اما شناسه پذیرنده از سامانه آورین دریافت نشد." },
		{ "failedToBindTerminalToMerchantInAvreen", "اتصال ترمینال به پذیرنده در سامانه آورین با خطا مواجه شد." },
		{ "youHaveToAcceptTheAgreementToContinue", "برای ادامه باید قرارداد را تایید کنید." },
		{ "generatingTheAgreementFailed", "تولید قرارداد با خطا مواجه شد." },
		{ "thisTerminalRequestIsWaitingForApproval", "این درخواست ترمینال در انتظار تایید است." },
		{ "thisTerminalRequestIsAlreadyApproved", "این درخواست ترمینال قبلاً تایید شده است." },
		{ "thisTerminalRequestIsNotWaitingForApproval", "این درخواست ترمینال در وضعیت انتظار تایید نیست." },
		{ "yourRequestHasBeenSubmittedAndIsAwaitingApproval", "درخواست شما ثبت شد و در انتظار تایید است." },
		{ "anUnexpectedErrorOccurredPleaseTryAgainLater", "خطای غیرمنتظره‌ای رخ داد. لطفاً مجدداً تلاش کنید." },

		// ===== Moadi =====
		{ "nameIsNotValid", "نام معتبر نیست." },
		{ "economicCodeIsRequired", "کد اقتصادی الزامی است." },
		{ "economicCodeIsNotValid", "کد اقتصادی معتبر نیست." },
		{ "legalEntityIsRequired", "نوع شخصیت حقوقی الزامی است." },
		{ "legalEntityIsNotValid", "نوع شخصیت حقوقی معتبر نیست." },
		{ "uniqueTaxCodeIsRequired", "شناسه یکتای مالیاتی الزامی است." },
		{ "uniqueTaxCodeIsNotValid", "شناسه یکتای مالیاتی معتبر نیست." },
		{ "ownerMobileIsRequired", "شماره موبایل مالک الزامی است." },
		{ "ownerMobileIsNotValid", "شماره موبایل مالک معتبر نیست." },
		{ "ownerNationalCodeIsRequired", "کد ملی مالک الزامی است." },
		{ "ownerNationalCodeIsNotValid", "کد ملی مالک معتبر نیست." },
		{ "taxpayerRequestNotFound", "درخواست مودی یافت نشد." },
		{ "thisTaxpayerRequestIsAlreadyApproved", "این درخواست مودی قبلاً تایید شده است." },
		{ "aTaxpayerWithThisEconomicCodeAlreadyExists", "مودی با این کد اقتصادی قبلاً ثبت شده است." },
		{ "taxpayerRegistrationInNamatSystemFailed", "ثبت مودی در سامانه نما با خطا مواجه شد." },
		// ===== Gold =====
		{ "idempotencyKeyIsRequired", "کلید یکتای درخواست الزامی است." },
		{ "idempotencyKeyIsNotValid", "کلید یکتای درخواست معتبر نیست." },
		{ "orderSideIsRequired", "نوع سفارش (خرید یا فروش) الزامی است." },
		{ "atLeastOneScopeIsRequired", "حداقل یک دسترسی الزامی است." },
		{ "sendExactlyOneOfBaseAmountOrQuoteAmountGreaterThanZero", "دقیقاً یکی از مقدار طلا یا مبلغ ریالی را بزرگ‌تر از صفر ارسال کنید." },
		{ "theGoldProviderIsNotConfigured", "سرویس‌دهنده طلا پیکربندی نشده است." },
		{ "theGoldProviderIsNotReachableRightNow", "در حال حاضر ارتباط با سرویس‌دهنده طلا برقرار نشد." },
		{ "theGoldProviderReturnedAnUnexpectedError", "سرویس‌دهنده طلا خطای پیش‌بینی‌نشده برگرداند." },
		{ "theGoldProviderRejectedTheRequestData", "اطلاعات ارسالی به سرویس‌دهنده طلا نامعتبر است." },
		{ "thePaginationCursorIsInvalidOrExpiredStartFromTheFirstPage", "کرسر صفحه‌بندی نامعتبر یا منقضی شده است. از صفحه اول شروع کنید." },
		{ "theRequestedGoldResourceWasNotFound", "منبع درخواستی در سرویس طلا یافت نشد." },
		{ "authenticationWithTheGoldProviderIsRequired", "برای دسترسی به سرویس طلا باید احراز هویت شوید." },
		{ "theGoldProviderCredentialsAreInvalid", "اعتبارنامه سرویس‌دهنده طلا نامعتبر است." },
		{ "theGoldProviderTokenIsInvalidOrExpired", "توکن سرویس‌دهنده طلا نامعتبر یا منقضی شده است." },
		{ "accessToThisGoldResourceIsDenied", "دسترسی به این بخش از سرویس طلا مجاز نیست." },
		{ "thisIPAddressIsNotAllowedByTheGoldProvider", "این آدرس IP از سوی سرویس‌دهنده طلا مجاز نیست." },
		{ "theGoldProviderClientAccountIsInactive", "حساب کلاینت سرویس طلا غیرفعال است." },
		{ "theGoldProviderTokenWasNotFound", "توکن سرویس‌دهنده طلا یافت نشد." },
		{ "theMaximumNumberOfActiveGoldTokensHasBeenReachedRevokeOneFirst", "حداکثر تعداد توکن‌های فعال طلا تکمیل شده است. ابتدا یک توکن را باطل کنید." },
		{ "theTokenIPWhitelistMustBeASubsetOfTheClientIPWhitelist", "لیست IP مجاز توکن باید زیرمجموعه لیست IP مجاز کلاینت باشد." },
		{ "tooManyRequestsToTheGoldProviderPleaseTryAgainShortly", "تعداد درخواست‌ها به سرویس طلا بیش از حد مجاز است. کمی بعد دوباره تلاش کنید." },
		{ "tooManyFailedAuthenticationAttemptsPleaseTryAgainShortly", "تعداد تلاش‌های ناموفق احراز هویت بیش از حد مجاز است. کمی بعد دوباره تلاش کنید." },
		{ "yourGoldBusinessAccountIsSuspended", "حساب کسب‌وکار طلای شما معلق شده است." },
		{ "thisTradePairIsNotSupported", "این جفت معاملاتی پشتیبانی نمی‌شود." },
		{ "theAssetPairDoesNotMatchTheRequest", "جفت دارایی ارسالی با درخواست مطابقت ندارد." },
		{ "theAssetWasNotFoundOrIsInactive", "دارایی یافت نشد یا غیرفعال است." },
		{ "theTradeRequestIsNotValid", "درخواست معامله نامعتبر است." },
		{ "theTradeAmountIsNotValid", "مقدار معامله نامعتبر است." },
		{ "theAmountHasMoreDecimalPlacesThanTheAssetAllows", "تعداد ارقام اعشار مقدار واردشده بیش از حد مجاز دارایی است." },
		{ "theAmountIsBelowTheMinimumTradeSize", "مبلغ واردشده برای حداقل معامله کافی نیست." },
		{ "thisIdempotencyKeyHasAlreadyBeenUsedGenerateANewOneForEachOrder", "این کلید قبلاً استفاده شده است. برای هر سفارش یک کلید جدید بسازید." },
		{ "yourOrderVolumeHasReachedTheLimitForTheCurrentTimeWindow", "حجم سفارش‌های شما در بازه زمانی فعلی به حد مجاز رسیده است." },
		{ "theOrderWasNotFound", "سفارش یافت نشد." },
		{ "yourGoldWalletBalanceIsNotEnough", "موجودی کیف پول طلای شما کافی نیست." },
		{ "theGoldPriceIsNotAvailableRightNowPleaseTryAgainShortly", "قیمت طلا در حال حاضر در دسترس نیست. کمی بعد دوباره تلاش کنید." },
		{ "yourGoldBalanceIsNotEnoughForThisOrder", "موجودی طلای شما برای این سفارش کافی نیست." },
		{ "yourGoldWalletIsLocked", "کیف پول طلای شما قفل است." },
		{ "theGoldTransactionWasNotFound", "تراکنش طلا یافت نشد." },
		{ "theGoldOrderWasNotCompletedAnyReservedAmountHasBeenReturned", "سفارش طلا انجام نشد. مبلغ رزروشده به کیف پول شما بازگشت." },
		{ "theGoldOrderIsBeingProcessedAndWillBeSettledShortly", "سفارش طلا در حال پردازش است و به‌زودی تسویه می‌شود." },
		{ "theGoldServiceIsTemporarilyUnavailablePleaseTryAgainLater", "سرویس طلا موقتاً در دسترس نیست. لطفاً بعداً تلاش کنید." },
		{ "buyingGoldIsClosedRightNow", "در حال حاضر امکان خرید طلا وجود ندارد. لطفاً بعداً تلاش کنید." },
		{ "sellingGoldIsClosedRightNow", "در حال حاضر امکان فروش طلا وجود ندارد. لطفاً بعداً تلاش کنید." },
		{ "goldTradingIsClosedOnThisSideRightNow", "معامله در این سمت در حال حاضر امکان‌پذیر نیست." },
		{ "aRequestedGoldScopeIsNotEnabledForThisAccount", "دست‌کم یکی از دسترسی‌های درخواستی طلا برای این حساب فعال نیست." },
		{ "theGoldProviderWalletIsLocked", "کیف پول سرویس‌دهنده طلا قفل است." },
		{ "theGoldProviderAccountBalanceIsNotEnough", "موجودی حساب کسب‌وکار نزد سرویس‌دهنده طلا کافی نیست." },

		// ===== Bill =====
		{ "billIdLengthMustBeBetween6And13Digits", "طول شناسه قبض باید بین ۶ تا ۱۳ رقم باشد." },
		{ "paymentIdLengthMustBeBetween6And13Digits", "طول شناسه پرداخت باید بین ۶ تا ۱۳ رقم باشد." },
		{ "billIdMustContainDigitsOnly", "شناسه قبض باید فقط شامل عدد باشد." },
		{ "paymentIdMustContainDigitsOnly", "شناسه پرداخت باید فقط شامل عدد باشد." },
		{ "billIdCheckDigitIsNotValid", "رقم کنترلی شناسه قبض معتبر نیست." },
		{ "paymentIdFirstControlDigitIsNotValid", "رقم کنترلی اول شناسه پرداخت معتبر نیست." },
		{ "paymentIdSecondControlDigitIsNotValid", "رقم کنترلی دوم شناسه پرداخت معتبر نیست." },
		{ "companyCodeIsUnknown", "کد شرکت شناسایی نشد." },
		{ "serviceTypeCodeIsUnknown", "کد نوع خدمات شناسایی نشد." },
		{ "billInformationCouldNotBeParsed", "اطلاعات قبض قابل پردازش نیست." },
		{ "theBillIsNotValid", "قبض معتبر نیست." },
		{ "theBillAmountIsNotAvailable", "مبلغ قبض در دسترس نیست." },
		{ "topUpTypeIsRequired", "نوع شارژ الزامی است." },
		{ "thisOperatorIsNotSupportedForDirectTopUp", "این اپراتور برای شارژ مستقیم پشتیبانی نمی‌شود." },
		{ "theSumOfMultiplexedAmountsMustBeEqualToTheTotalAmount", "مجموع مبالغ تسهیم باید با مبلغ کل برابر باشد." },
		{ "thisPaymentTypeIsNotSupportedByTheGateway", "این نوع پرداخت توسط درگاه پشتیبانی نمی‌شود." },

		// ===== Validation (previously missing) =====
		{ "BedIdRequired", "تخت الزامی است." },
		{ "CapacityRequired", "ظرفیت الزامی است." },
		{ "CityMinLength", "نام شهر باید بین ۲ تا ۱۰۰ کاراکتر باشد." },
		{ "CityRequired", "شهر الزامی است." },
		{ "ContractIdRequired", "قرارداد الزامی است." },
		{ "DepositRequired", "ودیعه الزامی است." },
		{ "DormIdRequired", "خوابگاه الزامی است." },
		{ "DrivingLicenceNumberInvalid", "شماره گواهینامه نامعتبر است." },
		{ "DrivingLicenceNumberRequired", "شماره گواهینامه الزامی است." },
		{ "HotelIdRequired", "هتل الزامی است." },
		{ "MonthlyRentRequired", "اجاره ماهانه الزامی است." },
		{ "NationalCodeNotValid", "کد ملی نامعتبر است." },
		{ "PricePerNightRequired", "قیمت هر شب الزامی است." },
		{ "TitleMaxLength", "عنوان بیش از حد طولانی است." },
		{ "TitleMinLength", "عنوان باید بین ۲ تا ۱۰۰ کاراکتر باشد." },
		{ "UsersRequired", "کاربران الزامی هستند." },
		{ "passwordLengthMustBeBetween4And100Characters", "رمز عبور باید بین ۴ تا ۱۰۰ کاراکتر باشد." },
		{ "amountIsNotValid", "مبلغ نامعتبر است." },
		{ "TicketNotFound", "تیکت یافت نشد." },

		// ===== Charge / Internet package =====
		{ "chargeServiceIsNotAvailable", "سرویس خرید شارژ و بسته اینترنت موقتاً در دسترس نیست. لطفاً چند دقیقه دیگر دوباره تلاش کنید." },
		{ "yourPreviousPurchaseIsStillInProgress", "خرید قبلی شما هنوز در حال انجام است. لطفاً چند لحظه صبر کنید." },
		{ "theMobileNumberIsNotValid", "شماره موبایل وارد شده معتبر نیست." },
		{ "theSelectedInternetPackageIsNoLongerAvailable", "بسته اینترنت انتخاب‌شده دیگر موجود نیست. لطفاً فهرست بسته‌ها را دوباره باز کنید." },
		{ "thePriceOfThisItemHasChangedPleaseTryAgain", "قیمت این مورد تغییر کرده است. لطفاً دوباره تلاش کنید." },
		{ "chargePinPurchasedSuccessfully", "رمز شارژ با موفقیت خریداری شد." },
		{ "simCardChargedSuccessfully", "سیم‌کارت با موفقیت شارژ شد." },
		{ "internetPackageActivatedSuccessfully", "بسته اینترنت با موفقیت فعال شد." },
		{ "yourTransactionIsBeingProcessed", "تراکنش شما در حال پردازش است. نتیجه تا چند دقیقه دیگر مشخص می‌شود و در صورت ناموفق بودن، مبلغ به کیف پول شما بازمی‌گردد." },

		// ===== Google login / password reset =====
		{ "googleSignInIsNotConfigured", "ورود با گوگل در دسترس نیست." },
		{ "googleTokenIsInvalid", "ورود با گوگل ناموفق بود. لطفاً دوباره تلاش کنید." },
		{ "googleEmailIsNotVerified", "ایمیل حساب گوگل شما تأیید نشده است." },
		{ "ifAnAccountExistsAResetCodeWasSent", "اگر حسابی با این ایمیل وجود داشته باشد، کد بازیابی برای آن ارسال شد." },
		{ "passwordResetCodeIsInvalidOrExpired", "کد بازیابی نامعتبر است یا منقضی شده است." },
		{ "passwordChangedSuccessfully", "رمز عبور شما تغییر کرد." },
		{ "passwordResetEmailSubject", "کد بازیابی رمز عبور" },
		{ "passwordResetEmailBody", "کد بازیابی رمز عبور شما {0} است و تا {1} دقیقه معتبر است. اگر این درخواست را نداده‌اید، این ایمیل را نادیده بگیرید." },

		// ===== Sport =====
		{ "sportNotFound", "ورزش پیدا نشد." },
		{ "sportIsRequired", "انتخاب ورزش الزامی است." },
		{ "sportTypeIsRequired", "انتخاب دقیقاً یک نوع ورزش الزامی است." },
		{ "thisSportAlreadyExists", "این ورزش قبلاً ثبت شده است." },
		{ "levelIsOutOfRange", "سطح خارج از محدوده مجاز است." },
		{ "thisSportIsAlreadyInYourProfile", "این ورزش قبلاً در پروفایل شما ثبت شده است." },
		{ "playerSportProfileNotFound", "پروفایل ورزشی پیدا نشد." },
		{ "sportIsInUseDisableItInstead", "این ورزش توسط بازیکنان استفاده شده است؛ به جای حذف، آن را غیرفعال کنید." },

		// ===== Tournament =====
		{ "tournamentNotFound", "تورنمنت پیدا نشد." },
		{ "formatIsRequired", "یک فرمت تورنمنت انتخاب کنید." },
		{ "thisFormatIsNotAvailableYet", "این فرمت هنوز در دسترس نیست." },
		{ "participantTypeIsRequired", "انفرادی یا دونفره را انتخاب کنید." },
		{ "capacityMustBeAtLeastTwo", "ظرفیت باید حداقل ۲ باشد." },
		{ "registrationIsClosed", "ثبت‌نام این تورنمنت بسته است." },
		{ "tournamentIsFull", "ظرفیت این تورنمنت تکمیل است." },
		{ "partnerEmailIsRequired", "ایمیل هم‌تیمی خود را وارد کنید." },
		{ "partnerNotFound", "بازیکنی با این ایمیل پیدا نشد." },
		{ "aPlayerIsAlreadyRegistered", "یکی از بازیکنان قبلاً در این تورنمنت ثبت‌نام کرده است." },
		{ "addThisSportToYourProfileFirst", "ابتدا این ورزش را به پروفایل خود اضافه کنید." },
		{ "levelIsNotInTheTournamentRange", "سطح شما در بازه این تورنمنت نیست." },
		{ "entryNotFound", "ثبت‌نام پیدا نشد." },
		{ "atLeastTwoApprovedEntriesAreRequired", "حداقل دو ثبت‌نام تأییدشده لازم است." },
		{ "tournamentHasStarted", "تورنمنت شروع شده است." },
		{ "matchNotFound", "بازی پیدا نشد." },
		{ "scoresAreInvalid", "امتیازها معتبر نیستند." },
		{ "thisFormatIsForIndividualPlayers", "این فرمت برای بازیکنان انفرادی است." },
		{ "teamNameIsRequired", "نام تیم را وارد کنید." },
		{ "playersMustBeAMultipleOfFour", "تعداد بازیکنان باید مضربی از ۴ باشد." },
		{ "notEnoughEntriesForThisFormat", "تعداد ثبت‌نام‌های تأییدشده برای این فرمت کافی نیست." },
		{ "tournamentHasNotStarted", "تورنمنت هنوز شروع نشده است." },
		{ "matchIsNotReady", "هنوز هر دو طرف این بازی مشخص نیستند." },
		{ "aLaterMatchIsAlreadyPlayed", "یک بازی بعدی به نتیجه این بازی وابسته است." },
		{ "scoresMustAddUpToPointsPerMatch", "جمع دو امتیاز باید برابر امتیاز هر بازی باشد." },
		{ "matchIsNotComplete", "بازی کامل نشده است." },
		{ "invalidSetScore", "امتیاز یکی از ست‌ها برای این ورزش معتبر نیست." },
		{ "drawsAreNotAllowedInKnockout", "بازی حذفی باید برنده داشته باشد." },
		{ "onlyAFinishedBoxLeagueCanContinue", "فقط باکس‌لیگ تمام‌شده به دوره بعد می‌رود." },
		{ "aFinishedGameCannotBeDeleted", "بازی تمام‌شده قابل حذف نیست." },
		{ "achievementNotFound", "افتخار پیدا نشد." },
		{ "bookingNotFound", "رزرو پیدا نشد." },
		{ "conversationNotFound", "گفتگو پیدا نشد." },
		{ "courtHasBookingsDeactivateItInstead", "این زمین رزرو دارد؛ به‌جای حذف، غیرفعالش کنید." },
		{ "courtNotFound", "زمین پیدا نشد." },
		{ "durationIsNotValid", "مدت زمان با بازه‌های زمین جور نیست." },
		{ "gameNotFound", "بازی پیدا نشد." },
		{ "levelIsNotInTheGameRange", "سطح شما در بازه‌ی این بازی نیست." },
		{ "locationIsNotValid", "موقعیت مکانی معتبر نیست." },
		{ "messageNotFound", "پیام پیدا نشد." },
		{ "postNotFound", "پست پیدا نشد." },
		{ "priceOrSlotIsNotValid", "قیمت یا طول بازه معتبر نیست." },
		{ "reportNotFound", "گزارش پیدا نشد." },
		{ "reportTypeIsRequired", "نوع گزارش را انتخاب کنید." },
		{ "teamsAreNotValid", "هر دو تیم باید از بازیکنان این بازی باشند و کسی در هر دو تیم نباشد." },
		{ "textIsRequired", "متن الزامی است." },
		{ "textIsTooLong", "متن خیلی طولانی است." },
		{ "thanksForYourReport", "ممنون، گزارش شما بررسی می‌شود." },
		{ "theGameHasNotStartedYet", "بازی هنوز شروع نشده است." },
		{ "theOrganizerCannotLeaveCancelInstead", "برگزارکننده نمی‌تواند خارج شود؛ بازی را لغو کنید." },
		{ "theStartTimeIsInThePast", "زمان شروع گذشته است." },
		{ "theVenueIsClosedAtThisTime", "مجموعه در این زمان بسته است." },
		{ "thisBookingCannotBeCancelled", "این رزرو قابل لغو نیست." },
		{ "thisBookingIsCancelled", "این رزرو لغو شده است." },
		{ "thisGameIsFull", "ظرفیت این بازی پر یا بسته است." },
		{ "thisTimeIsAlreadyBooked", "این زمان قبلاً رزرو شده است." },
		{ "thisVenueHasUpcomingBookings", "این مجموعه رزروهای پیش رو دارد." },
		{ "thisVenueIsNotTakingBookings", "این مجموعه فعلاً رزرو نمی‌پذیرد." },
		{ "thisVenueOnlyTakesOnlinePayment", "این مجموعه فقط پرداخت آنلاین می‌پذیرد." },
		{ "tournamentEntryFee", "ورودیه‌ی تورنمنت" },
		{ "tournamentEntryFees", "ورودیه‌های تورنمنت" },
		{ "tournamentEntryRefund", "بازگشت ورودیه‌ی تورنمنت" },
		{ "courtBookingPayment", "رزرو زمین" },
		{ "courtBookingRefund", "بازگشت وجه رزرو زمین" },
		{ "courtBookingSettlement", "تسویه‌ی رزرو زمین" },
		{ "userNotFound", "کاربر پیدا نشد." },
		{ "venueNotFound", "مجموعه پیدا نشد." },
		{ "youCannotBlockYourself", "نمی‌توانید خودتان را مسدود کنید." },
		{ "youCannotMessageThisUser", "امکان پیام دادن به این کاربر نیست." },
		{ "youHaveAlreadyJoined", "قبلاً عضو شده‌اید یا درخواست داده‌اید." },
		{ "yourShareIsAlreadyPaid", "سهم شما قبلاً پرداخت شده است." },
		// ===== Phases 5-8 =====
		{ "address", "آدرس" },
		{ "amount", "مبلغ" },
		{ "capacityIsFull", "ظرفیت تکمیل است." },
		{ "checkIn", "ورود" },
		{ "checkOut", "خروج" },
		{ "codeAlreadyExists", "این کد قبلاً ثبت شده است." },
		{ "deposit", "ودیعه" },
		{ "description", "توضیحات" },
		{ "discount", "تخفیف" },
		{ "dorm", "خوابگاه" },
		{ "dormContractTitle", "قرارداد اقامت در خوابگاه" },
		{ "dueDate", "سررسید" },
		{ "emergencyContact", "تماس اضطراری" },
		{ "endDate", "تاریخ پایان" },
		{ "endDateMustBeAfterStartDate", "تاریخ پایان باید بعد از تاریخ شروع باشد." },
		{ "extraCharge", "هزینه‌ی اضافه" },
		{ "guardian", "ولی" },
		{ "guest", "مهمان" },
		{ "guestFolio", "صورت‌حساب مهمان" },
		{ "vatIncluded", "مالیات بر ارزش افزوده‌ی ضمن مبلغ" },
		{ "planNotFound", "پلن پیدا نشد." },
		{ "planModulesRequired", "حداقل یک سیستم برای پلن انتخاب کنید." },
		{ "planPricesAreNotValid", "مدت یا قیمت پلن معتبر نیست." },
		{ "trialNotAvailable", "دوره‌ی آزمایشی رایگان برای این مجموعه در دسترس نیست." },
		{ "subscriptionNotFound", "اشتراک پرداخت‌نشده‌ای پیدا نشد." },
		{ "subscription", "اشتراک" },
		{ "subscriptionInactive", "اشتراک این مجموعه شامل این بخش نیست یا تمام شده است." },
		{ "organization", "مجموعه" },
		{ "guestSignature", "امضای مهمان" },
		{ "guests", "تعداد مهمانان" },
		{ "handoverDamage", "خسارت تحویل اتاق" },
		{ "hotel", "هتل" },
		{ "invoice", "صورت‌حساب" },
		{ "itemIsInUse", "این مورد در حال استفاده است و حذف نمی‌شود." },
		{ "itemNotFound", "مورد پیدا نشد." },
		{ "itemsAreRequired", "حداقل یک قلم اضافه کنید." },
		{ "lowStockAlert", "هشدار کمبود موجودی" },
		{ "minimumStayIsNotMet", "حداقل مدت اقامت برای این تاریخ‌ها رعایت نشده است." },
		{ "monthlyRent", "اجاره‌ی ماهانه" },
		{ "nationalCode", "کد ملی" },
		{ "newDormApplication", "درخواست اقامت جدید" },
		{ "newLeaveRequest", "درخواست مرخصی شبانه‌ی جدید" },
		{ "newMaintenanceRequest", "درخواست تعمیرات جدید" },
		{ "newShiftAssigned", "یک شیفت جدید برای شما ثبت شد" },
		{ "newTaskAssigned", "یک کار جدید به شما ارجاع شد" },
		{ "newVisitorRequest", "درخواست ملاقات جدید" },
		{ "nights", "تعداد شب" },
		{ "notEnoughStock", "موجودی این انبار کافی نیست." },
		{ "notPaid", "پرداخت‌نشده" },
		{ "organizationPlanExpired", "اشتراک مجموعه به پایان رسیده است." },
		{ "organizationPlanLimitReached", "به سقف اشتراک مجموعه رسیده‌اید." },
		{ "organizationSignature", "امضا و مهر مجموعه" },
		{ "paid", "پرداخت‌شده" },
		{ "paidAmount", "پرداخت‌شده" },
		{ "paymentReceipt", "رسید پرداخت" },
		{ "penalty", "جریمه" },
		{ "phoneNumber", "شماره‌ی تماس" },
		{ "purchase", "خرید" },
		{ "purchaseIsNotApproved", "این درخواست خرید هنوز تأیید نشده است." },
		{ "quantityIsNotValid", "مقدار معتبر نیست." },
		{ "remaining", "مانده" },
		{ "reservationCode", "کد رزرو" },
		{ "reservationExtended", "رزرو شما تمدید شد" },
		{ "reservationExtension", "تمدید اقامت" },
		{ "resident", "ساکن" },
		{ "residentSignature", "امضای ساکن" },
		{ "room", "اتاق" },
		{ "roomAndBed", "اتاق / تخت" },
		{ "roomChangeDifference", "مابه‌التفاوت تغییر اتاق" },
		{ "roomCharge", "هزینه‌ی اقامت" },
		{ "selectALaundryMachine", "یک دستگاه لباسشویی انتخاب کنید." },
		{ "selectTheTargetWarehouse", "انبار مقصد را انتخاب کنید." },
		{ "shiftIsAlreadyClosed", "این شیفت قبلاً بسته شده است." },
		{ "startDate", "تاریخ شروع" },
		{ "status", "وضعیت" },
		{ "stockAdjustment", "اصلاح موجودی" },
		{ "stockIn", "ورود کالا" },
		{ "stockOut", "خروج کالا" },
		{ "thisMealIsPast", "زمان این وعده گذشته است." },
		{ "thisRequestIsAlreadyReviewed", "این درخواست قبلاً بررسی شده است." },
		{ "thisReservationCannotBeChanged", "این رزرو قابل تغییر نیست." },
		{ "thisRoomIsClosedOnTheSelectedDates", "این اتاق در تاریخ‌های انتخاب‌شده بسته است." },
		{ "totalPrice", "مبلغ کل" },
		{ "unitIsRequired", "واحد الزامی است." },
		{ "violationRecorded", "یک تخلف برای شما ثبت شد" },
		{ "warningRecorded", "یک اخطار برای شما ثبت شد" },
		{ "youAlreadyHaveAnOpenApplication", "شما در این مکان یک درخواست باز دارید." },
		{ "youAlreadyReservedThis", "شما قبلاً این را رزرو کرده‌اید." },
		{ "youCannotApplyToThisPlace", "امکان ثبت درخواست در این مکان برای شما وجود ندارد." },
		{ "youCannotBookThisPlace", "امکان رزرو این مکان برای شما وجود ندارد." },
		{ "youHaveNoActiveContractHere", "شما در این مکان قرارداد فعالی ندارید." },
		{ "yourRequestIsApproved", "درخواست شما تأیید شد" },
		{ "yourRequestIsDone", "درخواست شما انجام شد" },
		{ "yourRequestIsRejected", "درخواست شما رد شد" },
		{ "dormApplicationApproved", "درخواست اقامت شما تأیید شد" },
		{ "dormApplicationRejected", "درخواست اقامت شما رد شد" },
		{ "dormApplicationWaitlisted", "درخواست اقامت شما در لیست انتظار قرار گرفت" },
		{ "dormApplicationUpdated", "درخواست اقامت شما به‌روز شد" },
	};

	public string Get(string key, string? locale = null) {
		if ((locale ?? httpContext.HttpContext?.Request.Headers["Locale"].FirstOrDefault() ?? "en") == "fa" && Fa.TryGetValue(key, out string? fa)) return fa;
		return En.GetValueOrDefault(key, key);
	}
}
