namespace SinaMN75U.InnerServices;

public interface ILocalizationService {
	string Get(string key, string? locale = null);
}

public class LocalizationService(IHttpContextAccessor httpContext) : ILocalizationService {
	private readonly Dictionary<string, string> _en = new() {
		{ "IdIsDuplicated", "This Id is already exist." },
		{ "RefreshTokenRequired", "Refresh Token Required." },
		{ "ZipCodeRequired", "ZipCode Is Required." },
		{ "LicencePlateRequired", "LicencePlate Is Required." },
		{ "ProductRequired", "Product Is Required." },
		{ "DrivingLicenceNumberRequired", "LicencePlate Is Required." },
		{ "IBanRequired", "IBan Is Required." },
		{ "ZipCodeInvalid", "ZipCode Is Invalid." },
		{ "LicencePlateInvalid", "LicencePlate Is Invalid." },
		{ "DrivingLicenceNumberInvalid", "LicencePlate Is Invalid." },
		{ "IBanInvalid", "IBan Is Invalid." },
		{ "SlugIsDuplicated", "This Slug is already exist." },
		{ "CodeIsDuplicated", "This Code is already exist." },
		{ "SimCardNumberIsDuplicated", "This Sim Card Number is already exist." },
		{ "SimCardSerialIsDuplicated", "This Sim Card Serial is already exist." },
		{ "ImeiIsDuplicated", "This Imei is already exist." },
		{ "TrackingNumberIsDuplicated", "This Tracking Number is already exist." },
		{ "EmailIsDuplicated", "This Email is already exist." },
		{ "UserNameIsDuplicated", "This UserName is already exist." },
		{ "PhoneNumberIsDuplicated", "This Phone Number is already exist." },
		{ "NationalCodeIsDuplicated", "This National Code is already exist." },
		{ "Required", "Required" },
		{ "InvalidCredentials", "Login Information is Wrong" },
		{ "PhoneNumberNotValid", "Phone number is not valid." },
		{ "PhoneNumberRequired", "Phone number is required." },
		{ "CommentRequired", "Comment is required." },
		{ "CommentNotFound", "Comment Not Found." },
		{ "ContentNotFound", "Content Not Found." },
		{ "ExamNotFound", "Exam Not Found." },
		{ "EmailRequired", "Email is required." },
		{ "UserNameRequired", "UserName is required." },
		{ "UserNameMinLenght", "UserName is not valid." },
		{ "TagsRequired", "Tags is Required" },
		{ "IdRequired", "Id is Required" },
		{ "OtpRequired", "Otp is Required" },
		{ "TitleRequired", "Title is Required" },
		{ "DescriptionRequired", "Description is Required" },
		{ "SubTitleRequired", "Subtitle is Required" },
		{ "FirstNameRequired", "First Name is Required" },
		{ "LastNameRequired", "Last Name is Required" },
		{ "NationalCodeRequired", "National Code is Required" },
		{ "StartDateRequired", "Start Date is Required" },
		{ "EndDateRequired", "End Date is Required" },
		{ "DateRequired", "Date is Required" },
		{ "PriceRequired", "Price is Required" },
		{ "UserIdRequired", "User is Required" },
		{ "ContractIdRequired", "Contract is Required" },
		{ "UserNotFound", "Account not found. Please check your details." },
		{ "EmailInvalid", "Please enter a valid email." },
		{ "UserNameInvalid", "Username is invalid. Please try another." },
		{ "FirstNameInvalid", "First Name is Invalid" },
		{ "LastNameInvalid", "Last Name is Invalid" },
		{ "NationalCodeInvalid", "National Code is Invalid" },
		{ "NationalCodeNotMatchWithPhoneNumberOwner", "National Code is not Match with Phone Number Owner." },
		{ "PasswordMinLength", "Password must be at least 6 characters." },
		{ "PasswordRequired", "Please enter a password." },
		{ "PasswordInvalid", "Password must be 6-100 characters." },
		{ "UserAlreadyExist", "Account already exists. Would you like to log in?" },
		{ "CategoryNotFound", "Category not found. Please try another." },
		{ "InvoiceNotFound", "Invoice not found. Please try another." },
		{ "ProductNotFound", "Product not found. Please check details." },
		{ "ProductDeleted", "Product removed successfully." },
		{ "ProductDeleteFailed", "Could not delete product. Please try later." },
		{ "PhoneNumberInvalid", "Please enter a valid phone number." },
		{ "AuthorizationRequired", "Please sign in to continue." },
		{ "MaxOtpReached", "Too many OTP requests. Please wait and try again." },
		{ "UserDeleted", "Account deleted successfully." },
		{ "AtLeastOneUserRequired", "At Least One User Required" },
		{ "CannotFollowYourself", "Cannot Follow Yourself" },
		{ "AlreadyFollowingUser", "Already Following User" },
		{ "AlreadyBookmarked", "Already Bookmarked" },
		{ "FollowSuccess", "Your now Following, " },
		{ "FollowRelationshipNotFound", "Error Finding the relation" },
		{ "FutureDateSelected", "Future Date Selected" },
		{ "BeforeDateSelected", "Wrong Date Selected" },
		{ "UnfollowSuccess", "You no Longer following, " },
		{ "ProductHasActiveContract", "Product Has Active Contract." },
		{ "ShahkarIsNotAvailableAtThisTime", "Shahkar is not Available at this Time, Please try again Later." },
		{ "TokenExpired", "Auth Token is Expired." },
		{ "InvalidAPIKey", "Invalid API key" },
		{ "InvalidJsonBody", "Invalid JSON body" },
		{ "InvalidBase64RequestBody", "Invalid base64 request body" },
		{ "RequestTooLarge", "Request too large" },
		{ "InvalidRequestFormat", "Invalid request format" },
		{ "InternalServerError", "Internal server error" },
		{ "YourDetailSubmittedSuccessfully", "Your Detail Submitted Successfully." },
		{ "SystemError", "System Error" },
		{ "ZipCodeMustBe10CharactersLong", "Zip Code must be 10 Characters Long." },
		{ "AddressWithThisZipCodeAlreadyExists", "Address with this ZipCode already exists." },
		{ "BalanceIsLow", "Your Balance is Not Enough." },
		{ "SenderWalletNotFound", "Sender Wallet Not Found" },
		{ "ReceiverWalletNotFound", "Receiver Wallet Not Found" },
		{ "TransferMoneyDone", "Transfer Money Successful" },
		{ "WalletForThisUserAlreadyExists", "User Already has Wallet." },
		{ "AddressNotFound", "Address Not Found" },
		{ "BankAccountNotFound", "Bank Account Not Found." },
		{ "AddressUpdatedSuccessfully", "Address Updated Successfully" },
		{ "AddressDeletedSuccessfully", "Address Deleted Successfully" },
		{ "LicencePlateMinMaxLenght", "Licence Plate can't be more than 10 Characters." },
		{ "TerminalNotFound", "Terminal Not Found." },
		{ "EntrancePriceRequired", "Entrance Price Required." },
		{ "HourlyPriceRequired", "Hourly Price Required." },
		{ "DailyPriceRequired", "Daily Price Required." },
		{ "AmountRequired", "Amount Required." },
		{ "TrackingNumberRequired", "Tracking Number Required." },
		{ "NumberRequired", "Number Required." },
		{ "SerialRequired", "Serial Required." },
		{ "YouDoNotHaveClearanceToDoThisAction", "You Do Not have Clearance to do this Action." }
	};

	private readonly Dictionary<string, string> _fa = new() {
		{ "IdIsDuplicated", "آیدی تکراری است." },
		{ "RefreshTokenRequired", "توکن الزامیست" },
		{ "ZipCodeRequired", "کد پستی الزامی است." },
		{ "LicencePlateRequired", "شماره پلاک الزامی است." },
		{ "DrivingLicenceNumberRequired", "شماره گواهینامه الزامی است." },
		{ "IBanRequired", "کد پستی اشتباه است." },
		{ "ProductRequired", "محصول الزامی است." },
		{ "ZipCodeInvalid", "کد پستی اشتباه است." },
		{ "LicencePlateInvalid", "شماره پلاک اشتباه است." },
		{ "DrivingLicenceNumberInvalid", "شماره گواهینامه اشتباه است." },
		{ "IBanInvalid", "شماره شبا اشتباه است." },
		{ "SlugIsDuplicated", "اسلاگ تکراری است." },
		{ "CodeIsDuplicated", "کد تکراری است." },
		{ "SimCardNumberIsDuplicated", "شماره سیمکارت تکراری است." },
		{ "SimCardSerialIsDuplicated", "سریال سیمکارت تکراری است." },
		{ "ImeiIsDuplicated", "IMEI تکراری است." },
		{ "TrackingNumberIsDuplicated", "کد رهگیری تکراری است." },
		{ "EmailIsDuplicated", "ایمیل تکراری است." },
		{ "UserNameIsDuplicated", "نام کاربری تکراری است." },
		{ "PhoneNumberIsDuplicated", "شماره موبایل تکراری است." },
		{ "NationalCodeIsDuplicated", "کد ملی تکراری است." },
		{ "Required", "مورد نیاز" },
		{ "InvalidCredentials", "اطلاعات ورود اشتباه است" },
		{ "PhoneNumberNotValid", "شماره تلفن معتبر نیست." },
		{ "PhoneNumberRequired", "شماره تلفن الزامی است." },
		{ "CommentRequired", "نظر الزامی است." },
		{ "CommentNotFound", "نظر یافت نشد." },
		{ "ContentNotFound", "محتوا یافت نشد." },
		{ "ExamNotFound", "آزمون یافت نشد." },
		{ "EmailRequired", "ایمیل الزامی است." },
		{ "UserNameRequired", "نام کاربری الزامی است." },
		{ "UserNameMinLenght", "نام کاربری معتبر نیست." },
		{ "TagsRequired", "برچسب‌ها الزامی است" },
		{ "IdRequired", "شناسه الزامی است" },
		{ "OtpRequired", "کد تایید الزامی است" },
		{ "TitleRequired", "عنوان الزامی است" },
		{ "DescriptionRequired", "توضیحات الزامی است" },
		{ "SubTitleRequired", "عنوان فرعی الزامی است" },
		{ "FirstNameRequired", "نام الزامی است" },
		{ "LastNameRequired", "نام خانوادگی الزامی است" },
		{ "NationalCodeRequired", "کد ملی الزامی است" },
		{ "StartDateRequired", "تاریخ شروع الزامی است" },
		{ "EndDateRequired", "تاریخ پایان الزامی است" },
		{ "DateRequired", "تاریخ الزامی است" },
		{ "PriceRequired", "قیمت الزامی است" },
		{ "UserIdRequired", "کاربر الزامی است" },
		{ "ContractIdRequired", "قرارداد الزامی است" },
		{ "UserNotFound", "حساب کاربری یافت نشد. لطفاً جزئیات خود را بررسی کنید." },
		{ "EmailInvalid", "لطفاً یک ایمیل معتبر وارد کنید." },
		{ "UserNameInvalid", "نام کاربری نامعتبر است. لطفاً دیگری را امتحان کنید." },
		{ "FirstNameInvalid", "نام نامعتبر است" },
		{ "LastNameInvalid", "نام خانوادگی نامعتبر است" },
		{ "NationalCodeInvalid", "کد ملی نامعتبر است" },
		{ "NationalCodeNotMatchWithPhoneNumberOwner", "کد ملی با صاحب شماره تلفن مطابقت ندارد." },
		{ "PasswordMinLength", "رمز عبور باید حداقل 6 کاراکتر باشد." },
		{ "PasswordRequired", "لطفاً رمز عبور را وارد کنید." },
		{ "PasswordInvalid", "رمز عبور باید بین 6 تا 100 کاراکتر باشد." },
		{ "UserAlreadyExist", "حساب کاربری از قبل وجود دارد. آیا مایل به ورود هستید؟" },
		{ "CategoryNotFound", "دسته بندی یافت نشد. لطفاً دیگری را امتحان کنید." },
		{ "InvoiceNotFound", "فاکتور یافت نشد. لطفاً دیگری را امتحان کنید." },
		{ "ProductNotFound", "محصول یافت نشد. لطفاً جزئیات را بررسی کنید." },
		{ "ProductDeleted", "محصول با موفقیت حذف شد." },
		{ "ProductDeleteFailed", "حذف محصول امکان پذیر نبود. لطفاً بعداً دوباره امتحان کنید." },
		{ "PhoneNumberInvalid", "لطفاً یک شماره تلفن معتبر وارد کنید." },
		{ "AuthorizationRequired", "لطفاً برای ادامه وارد شوید." },
		{ "MaxOtpReached", "تعداد درخواست‌های کد تایید زیاد است. لطفاً صبر کرده و دوباره امتحان کنید." },
		{ "UserDeleted", "حساب کاربری با موفقیت حذف شد." },
		{ "AtLeastOneUserRequired", "حداقل یک کاربر مورد نیاز است" },
		{ "CannotFollowYourself", "امکان فالو کردن خودتان وجود ندارد" },
		{ "AlreadyFollowingUser", "از قبل این کاربر را فالو می‌کنید" },
		{ "AlreadyBookmarked", "از قبل بوکمارک شده است" },
		{ "FollowSuccess", "شما اکنون در حال فالو کردن هستید، " },
		{ "FollowRelationshipNotFound", "خطا در یافتن رابطه" },
		{ "FutureDateSelected", "تاریخ آینده انتخاب شده است" },
		{ "BeforeDateSelected", "تاریخ اشتباه انتخاب شده است" },
		{ "UnfollowSuccess", "شما دیگر فالو نمی‌کنید، " },
		{ "ProductHasActiveContract", "محصول دارای قرارداد فعال است." },
		{ "ShahkarIsNotAvailableAtThisTime", "شاهکار در این زمان در دسترس نیست، لطفاً بعداً دوباره امتحان کنید." },
		{ "TokenExpired", "توکن احراز هویت منقضی شده است." },
		{ "InvalidAPIKey", "کلید API نامعتبر است" },
		{ "InvalidJsonBody", "بدنه JSON نامعتبر است" },
		{ "InvalidBase64RequestBody", "بدنه درخواست base64 نامعتبر است" },
		{ "RequestTooLarge", "درخواست بیش از حد بزرگ است" },
		{ "InvalidRequestFormat", "قالب درخواست نامعتبر است" },
		{ "InternalServerError", "خطای داخلی سرور" },
		{ "YourDetailSubmittedSuccessfully", "جزئیات شما با موفقیت ارسال شد." },
		{ "SystemError", "خطای سیستم" },
		{ "ZipCodeMustBe10CharactersLong", "کد پستی باید 10 کاراکتر باشد." },
		{ "AddressWithThisZipCodeAlreadyExists", "آدرسی با این کد پستی از قبل وجود دارد." },
		{ "BalanceIsLow", "موجودی شما کافی نیست." },
		{ "SenderWalletNotFound", "کیف پول فرستنده یافت نشد" },
		{ "ReceiverWalletNotFound", "کیف پول گیرنده یافت نشد" },
		{ "TransferMoneyDone", "انتقال پول با موفقیت انجام شد" },
		{ "WalletForThisUserAlreadyExists", "کاربر از قبل کیف پول دارد." },
		{ "AddressNotFound", "آدرس یافت نشد" },
		{ "BankAccountNotFound", "حساب بانکی یافت نشد." },
		{ "AddressUpdatedSuccessfully", "آدرس با موفقیت به روز شد" },
		{ "AddressDeletedSuccessfully", "آدرس با موفقیت حذف شد" },
		{ "LicencePlateMinMaxLenght", "طول پلاک خودرو نمیتواند بیشتر از ۱۰ کاراکتر باشد." },
		{ "TerminalNotFound", "ترمینال یافت نشد." },
		{ "EntrancePriceRequired", "مبلغ ورودی الزامی است" },
		{ "HourlyPriceRequired", "مبلغ ساعتی الزامی است" },
		{ "DailyPriceRequired", "مبلغ روزانه الزامی است" },
		{ "AmountRequired", "مبلغ الزامی است" },
		{ "NumberRequired", "شماره الزامی است" },
		{ "TrackingNumberRequired", "کد رهگیری الزامی است" },
		{ "SerialRequired", "سریال الزامی است" },
		{ "YouDoNotHaveClearanceToDoThisAction", "شما مجاز به انجام این عملیات نیستید." }
	};

	public string Get(string key, string? locale = null) {
		string l = locale ?? httpContext.HttpContext?.Request.Headers["Locale"].FirstOrDefault() ?? "en";
		try {
			if (l == "fa") return _fa[key];
			return _en[key];
		}
		catch (Exception) {
			return string.Empty;
		}
	}
}